// export const itemMaster = [

//     { label: 'Agama', icon: 'fa fa-fw fa-bars', routerLink: ['/master-agama'] },
//     { label: 'Alamat', icon: 'fa fa-fw fa-bars', routerLink: ['/master-alamat'] },
//     { label: 'Alat', icon: 'fa fa-fw fa-bars', routerLink: ['/master-alat'] },
//     { label: 'Asal', icon: 'fa fa-fw fa-bars', routerLink: ['/master-asal'] },
//     { label: 'Awards', icon: 'fa fa-fw fa-bars', routerLink: ['/master-awards'] },
//     { label: 'Award Offence', icon: 'fa fa-fw fa-bars', routerLink: ['/award-offence'] },

//     { label: 'Bahasa', icon: 'fa fa-fw fa-bars', routerLink: ['/master-bahasa'] },

//     //{ label: 'Contoh', icon: 'fa fa-fw fa-bars', routerLink: ['/master-contoh'] },

//     { label: 'Dokumen', icon: 'fa fa-fw fa-bars', routerLink: ['/master-dokumen'] },
//     { label: 'Desa Kelurahan', icon: 'fa fa-fw fa-bars', routerLink: ['/master-desaKelurahan'] },
//     { label: 'Departemen', icon: 'fa fa-fw fa-bars', routerLink: ['/master-departemen'] },
//     { label: 'Detail Jenis Produk', icon: 'fa fa-fw fa-bars', routerLink: ['/detail-jenis-produk'] },

//     { label: 'Eselon', icon: 'fa fa-fw fa-bars', routerLink: ['/master-eselon'] },
//     { label: 'Event', icon: 'fa fa-fw fa-bars', routerLink: ['/master-event'] },

//     { label: 'Golongan Darah', icon: 'fa fa-fw fa-bars', routerLink: ['/master-golonganDarah'] },
//     { label: 'Golongan Pegawai', icon: 'fa fa-fw fa-bars', routerLink: ['/master-golonganPegawai'] },

//     { label: 'Hari Libur', icon: 'fa fa-fw fa-bars', routerLink: ['/master-harilibur'] },
//     { label: 'Hari', icon: 'fa fa-fw fa-bars', routerLink: ['/master-hari'] },
//     { label: 'Hubungan Keluarga', icon: 'fa fa-fw fa-bars', routerLink: ['/master-hubungan-keluarga'] },
//     { label: 'Histori Login Modul Aplikasi', icon: 'fa fa-fw fa-bars', routerLink: ['/master-histori-login-modul-aplikasi'] },
//     { label: 'Histori Login User', icon: 'fa fa-fw fa-bars', routerLink: ['/master-histori-login-user'] },
//     { label: 'Histori Pinjaman', icon: 'fa fa-fw fa-bars', routerLink: ['/historipinjaman'] },

//     { label: 'Jabatan', icon: 'fa fa-fw fa-bars', routerLink: ['/master-jabatan'] },
//     { label: 'Jenis Paket', icon: 'fa fa-fw fa-bars', routerLink: ['/jenis-paket'] },
//     { label: 'Jenis Pegawai', icon: 'fa fa-fw fa-bars', routerLink: ['/master-jenis-pegawai'] },
//     { label: 'Jenis Dokumen', icon: 'fa fa-fw fa-bars', routerLink: ['/master-jenis-dokumen'] },
//     { label: 'Jenis Kelamin', icon: 'fa fa-fw fa-bars', routerLink: ['/master-jenis-kelamin'] },
//     { label: 'Jenis Profile', icon: 'fa fa-fw fa-bars', routerLink: ['/master-jenis-profile'] },
//     { label: 'Jenis Rekanan', icon: 'fa fa-fw fa-bars', routerLink: ['/master-jenis-rekanan'] },
//     { label: 'Jenis Tarif', icon: 'fa fa-fw fa-bars', routerLink: ['/master-jenis-tarif'] },
//     { label: 'Jenis Keputusan', icon: 'fa fa-fw fa-bars', routerLink: ['/master-jenis-keputusan'] },
//     { label: 'Jenis Alamat', icon: 'fa fa-fw fa-bars', routerLink: ['/master-jenis-alamat'] },
//     { label: 'Jenis Perawatan', icon: 'fa fa-fw fa-bars', routerLink: ['/master-jenis-perawatan'] },
//     { label: 'Jenis Komponen', icon: 'fa fa-fw fa-bars', routerLink: ['/jenis-komponen'] },
//     { label: 'Jenis Produk', icon: 'fa fa-fw fa-bars', routerLink: ['/jenis-produk'] },

//     { label: 'Kategori Aset', icon: 'fa fa-fw fa-bars', routerLink: ['/kategori-aset'] },
//     { label: 'Kategori Gaji', icon: 'fa fa-fw fa-bars', routerLink: ['/kategori-gaji'] },
//     { label: 'Kecamatan', icon: 'fa fa-fw fa-bars', routerLink: ['/master-kecamatan'] },
//     { label: 'Kelompok User', icon: 'fa fa-fw fa-bars', routerLink: ['/master-kelompok-user'] },
//     { label: 'Kelompok Pegawai', icon: 'fa fa-fw fa-bars', routerLink: ['/master-kelompok-pegawai'] },
//     { label: 'Kelompok Pemilik Profile', icon: 'fa fa-fw fa-bars', routerLink: ['/master-kelompok-pemilik-profile'] },
//     { label: 'Kelompok Transaksi', icon: 'fa fa-fw fa-bars', routerLink: ['/master-kelompok-transaksi'] },
//     { label: 'Kelompok Produk', icon: 'fa fa-fw fa-bars', routerLink: ['/kelompok-produk'] },
//     { label: 'Kategori Pegawai', icon: 'fa fa-fw fa-bars', routerLink: ['/master-kategori-pegawai'] },
//     { label: 'Kategori Dokumen', icon: 'fa fa-fw fa-bars', routerLink: ['/master-kategori-dokumen'] },
//     { label: 'Keterangan Alasan', icon: 'fa fa-fw fa-bars', routerLink: ['/keterangan-alasan'] },
//     { label: 'Kelompok Shift Kerja', icon: 'fa fa-fw fa-bars', routerLink: ['/kelompok-shift-kerja'] },
//     { label: 'Kualifikasi Jurusan', icon: 'fa fa-fw fa-bars', routerLink: ['/master-kualifikasi-jurusan'] },
//     { label: 'Komponen', icon: 'fa fa-fw fa-bars', routerLink: ['/komponen'] },
//     { label: 'Komponen Hasil', icon: 'fa fa-fw fa-bars', routerLink: ['/komponen-hasil'] },
//     { label: 'Komponen', icon: 'fa fa-fw fa-bars', routerLink: ['/komponen'] },
//     { label: 'Komponen Hasil', icon: 'fa fa-fw fa-bars', routerLink: ['/komponen-hasil'] },
//     { label: 'Kondisi Produk', icon: 'fa fa-fw fa-bars', routerLink: ['/kondisi-produk'] },
//     { label: 'Kelas', icon: 'fa fa-fw fa-bars', routerLink: ['/master-kelas'] },
//     { label: 'Kalender', icon: 'fa fa-fw fa-bars', routerLink: ['/master-kalender'] },
//     { label: 'Kota Kabupaten', icon: 'fa fa-fw fa-bars', routerLink: ['/master-kota-kabupaten'] },
//     { label: 'Kelompok Evaluasi', icon: 'fa fa-fw fa-bars', routerLink: ['/kelompok-evaluasi'] },

//     { label: 'Level Tingkat', icon: 'fa fa-fw fa-bars', routerLink: ['/master-level-tingkat'] },
//     { label: 'Lokasi', icon: 'fa fa-fw fa-bars', routerLink: ['/master-lokasi '] },

//     { label: 'Map Kalender To Hari Libur', icon: 'fa fa-fw fa-bars', routerLink: ['/map-kalender-to-hari-libur'] },
//     { label: 'Map Objek Modul To Aplikasi', icon: 'fa fa-fw fa-bars', routerLink: ['/master-map-objek-modul-to-modul-aplikasi'] },
//     { label: 'Map Paket Medical To Produk', icon: 'fa fa-fw fa-bars', routerLink: ['/map-paket-medical-to-produk'] },
//     { label: 'Map Pegawai To Modul Aplikasi', icon: 'fa fa-fw fa-bars', routerLink: ['/master-map-pegawai-to-modul-aplikasi'] },
//     { label: 'Map User Login To Ruangan', icon: 'fa fa-fw fa-bars', routerLink: ['/master-mapuserloginruangan'] },
//     { label: 'Map Objek Modul To Departemen', icon: 'fa fa-fw fa-bars', routerLink: ['/master-mapobjekmoduldepartemen'] },
//     { label: 'Map Angka To Bulan', icon: 'fa fa-fw fa-bars', routerLink: ['/map-angka-to-bulan'] },
//     { label: 'Map Angka To Hari', icon: 'fa fa-fw fa-bars', routerLink: ['/map-angka-to-hari'] },
//     { label: 'Map Angka To Romawi', icon: 'fa fa-fw fa-bars', routerLink: ['/map-angka-to-romawi'] },
//     { label: 'Map Jabatan To Pangkat', icon: 'fa fa-fw fa-bars', routerLink: ['/map-jabatan-to-pangkat'] },
//     { label: 'Map Jenis Pegawai To Jabatan', icon: 'fa fa-fw fa-bars', routerLink: ['/map-jenispegawai-to-jabatan'] },
//     { label: 'Map Jenis Pegawai To Departemen', icon: 'fa fa-fw fa-bars', routerLink: ['/map-jenispegawai-to-departemen'] },
//     { label: 'Map Kelompok Transaksi To Posting', icon: 'fa fa-fw fa-bars', routerLink: ['/map-map-kelompoktransaksi-posting'] },
//     { label: 'Messaging Objek Modul Aplikasi', icon: 'fa fa-fw fa-bars', routerLink: ['/master-messaging-objek-modul-aplikasi'] },
//     { label: 'Messaging', icon: 'fa fa-fw fa-bars', routerLink: ['/master-messaging'] },
//     { label: 'Map Objek Modul To Kelompok User', icon: 'fa fa-fw fa-bars', routerLink: ['/map-objek-modul-to-kelompok-user'] },
//     { label: 'Map Kelompok Shift To Shift', icon: 'fa fa-fw fa-bars', routerLink: ['/map-kelompok-shift-to-shift'] },
//     { label: 'Map Event To Produk', icon: 'fa fa-fw fa-bars', routerLink: ['/map-event-to-produk'] },
//     { label: 'Modul Aplikasi', icon: 'fa fa-fw fa-bars', routerLink: ['/master-modul-aplikasi'] },
//     { label: 'Mata Uang', icon: 'fa fa-fw fa-bars', routerLink: ['/master-matauang'] },

//     { label: 'Negara', icon: 'fa fa-fw fa-bars', routerLink: ['/master-negara'] },

//     { label: 'Objek Modul Aplikasi', icon: 'fa fa-fw fa-bars', routerLink: ['/master-objek-modul-aplikasi'] },
//     { label: 'Object Modul Aplikasi Relasi', icon: 'fa fa-fw fa-bars', routerLink: ['/master-objectModulAplikasiRelasi'] },
//     { label: 'Object Modul Aplikasi Relasi', icon: 'fa fa-fw fa-bars', routerLink: ['/master-objectModulAplikasiRelasi'] },

//     { label: 'Paket', icon: 'fa fa-fw fa-bars', routerLink: ['/paket'] },
//     { label: 'Propinsi', icon: 'fa fa-fw fa-bars', routerLink: ['/master-propinsi'] },
//     { label: 'Profile', icon: 'fa fa-fw fa-bars', routerLink: ['/master-profile'] },
//     { label: 'Pendidikan', icon: 'fa fa-fw fa-bars', routerLink: ['/master-pendidikan'] },
//     { label: 'Pemilik Profile', icon: 'fa fa-fw fa-bars', routerLink: ['/master-pemilik-profile'] },
//     { label: 'Penghasilan Tidak Kena Pajak', icon: 'fa fa-fw fa-bars', routerLink: ['/master-penghasilan-tidak-kena-pajak'] },
//     { label: 'Pegawai', icon: 'fa fa-fw fa-bars', routerLink: ['/master-pegawai'] },
//     { label: 'Printer', icon: 'fa fa-fw fa-bars', routerLink: ['/master-printer'] },
//     { label: 'Pangkat', icon: 'fa fa-fw fa-bars', routerLink: ['/master-pangkat'] },
//     { label: 'Profile Histori Lowongan dan KJ-T', icon: 'fa fa-fw fa-bars', routerLink: ['/master-profileHistoriLowongan-KJ'] },
//     { label: 'Profile Histori STMS', icon: 'fa fa-fw fa-bars', routerLink: ['/master-profileHistoriStms'] },
//     { label: 'Pegawai Bahasa', icon: 'fa fa-fw fa-bars', routerLink: ['/master-pegawai-bahasa'] },
//     { label: 'Profil Histori Visi Misi Tujuan', icon: 'fa fa-fw fa-bars', routerLink: ['/profil-histori-visi-misi-tujuan'] },
//     { label: 'Pegawai Dokumen', icon: 'fa fa-fw fa-bars', routerLink: ['/master-pegawai-dokumen'] },
//     { label: 'Profile Histori Laporan', icon: 'fa fa-fw fa-bars', routerLink: ['/profile-histori-laporan'] },
//     { label: 'Profile Histori Lowongan S & D_T', icon: 'fa fa-fw fa-bars', routerLink: ['/profile-histori-lowongan-s-d-t'] },
//     { label: 'Pengajuan Pinjaman', icon: 'fa fa-fw fa-bars', routerLink: ['/pengajuanpinjaman'] },
//     { label: 'Pegawai SK Fasilitas', icon: 'fa fa-fw fa-bars', routerLink: ['/pegawai-sk-fasilitas'] },
//     { label: 'Pegawai SK Gaji', icon: 'fa fa-fw fa-bars', routerLink: ['/pegawai-sk-gaji'] },
//     { label: 'Pegawai SK Gaji BA', icon: 'fa fa-fw fa-bars', routerLink: ['/pegawai-sk-gaji-ba'] },
//     { label: 'Pegawai SK Gaji BAK', icon: 'fa fa-fw fa-bars', routerLink: ['/pegawai-sk-gaji-bak'] },
//  //   { label: 'Pegawai SK Loan', icon: 'fa fa-fw fa-bars', routerLink: ['/pegawai-sk-loan'] },
//     { label: 'Pegawai SK Medical', icon: 'fa fa-fw fa-bars', routerLink: ['/pegawai-sk-medical'] },
//     { label: 'Pegawai Struktur Gaji By Golongan', icon: 'fa fa-fw fa-bars', routerLink: ['/pegawai-struktur-gaji-by-golongan'] },
//     { label: 'Pegawai Struktur Gaji By Ja', icon: 'fa fa-fw fa-bars', routerLink: ['/pegawai-struktur-gaji-by-ja'] },
//     { label: 'Pegawai Struktur Gaji By JaPe', icon: 'fa fa-fw fa-bars', routerLink: ['/pegawai-struktur-gaji-by-jape'] },
//     { label: 'Pegawai Struktur Gaji By LTJa', icon: 'fa fa-fw fa-bars', routerLink: ['/pegawai-struktur-gaji-by-ltja'] },
//     { label: 'Pegawai Struktur Gaji By MaKaPe', icon: 'fa fa-fw fa-bars', routerLink: ['/pegawai-struktur-gaji-by-makape'] },
//     { label: 'Produk', icon: 'fa fa-fw fa-bars', routerLink: ['/produk'] },

//     { label: 'Rekanan', icon: 'fa fa-fw fa-bars', routerLink: ['/master-rekanan'] },
//     { label: 'Ruangan', icon: 'fa fa-fw fa-bars', routerLink: ['/master-ruangan'] },
//     { label: 'Range', icon: 'fa fa-fw fa-bars', routerLink: ['/master-range'] },

//     { label: 'Satuan Kerja', icon: 'fa fa-fw fa-bars', routerLink: ['/master-satuan-kerja'] },
//     { label: 'Suku', icon: 'fa fa-fw fa-bars', routerLink: ['/master-suku'] },
//     { label: 'Setting Data Fixed', icon: 'fa fa-fw fa-bars', routerLink: ['/master-settingdatafixed'] },
//     { label: 'Status', icon: 'fa fa-fw fa-bars', routerLink: ['/master-status'] },
//     { label: 'Spesifikasi', icon: 'fa fa-fw fa-bars', routerLink: ['/master-spesifikasi'] },
//     { label: 'Surat Keputusan', icon: 'fa fa-fw fa-bars', routerLink: ['/surat-keputusan'] },
//     { label: 'Struktur Nomor', icon: 'fa fa-fw fa-bars', routerLink: ['/master-struktur-nomor'] },
//     { label: 'Struktur Nomor Detail', icon: 'fa fa-fw fa-bars', routerLink: ['/master-struktur-nomor-detail'] },
//     { label: 'Shift Kerja', icon: 'fa fa-fw fa-bars', routerLink: ['/shift-kerja'] },
//     { label: 'Shift Kerja Formulasi', icon: 'fa fa-fw fa-bars', routerLink: ['/shift-kerja-formulasi'] },
//     { label: 'Surat Keputusan Approval', icon: 'fa fa-fw fa-bars', routerLink: ['/surat-keputusan-approval'] },

//     { label: 'Type Profile', icon: 'fa fa-fw fa-bars', routerLink: ['/master-type-profile'] },
//     { label: 'Tahapan Akreditasi', icon: 'fa fa-fw fa-bars', routerLink: ['/master-tahapan-akreditasi'] },
//     { label: 'Title Pegawai', icon: 'fa fa-fw fa-bars', routerLink: ['/master-title-pegawai'] },
//     { label: 'Type Pegawai', icon: 'fa fa-fw fa-bars', routerLink: ['/master-type-pegawai'] },
//     { label: 'Type Data Object', icon: 'fa fa-fw fa-bars', routerLink: ['/type-data-object'] },

//     { label: 'Unit Laporan', icon: 'fa fa-fw fa-bars', routerLink: ['/master-unit-laporan'] },
//     { label: 'Jenis Pajak', icon: 'fa fa-fw fa-bars', routerLink: ['/master-jenis-pajak'] },
//     { label: 'Master Pajak', icon: 'fa fa-fw fa-bars', routerLink: ['/master-pajak'] },
//     { label: 'Master Objek Pajak', icon: 'fa fa-fw fa-bars', routerLink: ['/master-objek-pajak'] },
//     { label: 'Master PTKP', icon: 'fa fa-fw fa-bars', routerLink: ['/master-ptkp'] },
//     { label: 'Master Pegawai Sk Pajak', icon: 'fa fa-fw fa-bars', routerLink: ['/master-pegawai-sk-pajak'] },
//     { label: 'Modul User', icon: 'fa fa-fw fa-bars', routerLink: ['/modul-user'] },

// ];