export const routeMasterData = [
    // Global Menu  
    { path: 'master-printer', loadChildren: './page/master/master-aset.module#PrinterModule' },
    { path: 'alat', loadChildren: './page/master/master-aset.module#AlatModule' },
    { path: 'master-dokumen', loadChildren: './page/master/master-dokumen.module#DokumenModule' },
    { path: 'jenis-pajak', loadChildren: './page/master/master-pajak.module#JenisPajakModule' },

    //Menu Profile Perusahaan
    { path: 'master-kelompok-pemilik-profile-profile', loadChildren: './page/master/master-profile.module#KelompokPemilikProfileModule' },
    { path: 'master-pemilik-profile-profile', loadChildren: './page/master/master-profile.module#PemilikProfileModule' },
    { path: 'master-jenis-profile-profile', loadChildren: './page/master/master-profile.module#JenisProfileModule' },
    { path: 'master-ruangan-profile', loadChildren: './page/master/master-profile.module#RuanganModule' },
    { path: 'master-profile-profile', loadChildren: './page/master/master-profile.module#ProfileModule' },
    { path: 'master-lokasi-kerja', loadChildren: './page/master/master-profile.module#LokasiKerjaModule' },
    { path: 'master-ruangan', loadChildren: './page/master/master-profile.module#RuanganUnitKerjaModule' },
    { path: 'master-profile', loadChildren: './page/master/master-profile.module#ProfileKlinikModule' },

    //Menu Struktur Organisasi
    { path: 'master-departemen-struktur', loadChildren: './page/master/master-profile.module#DepartemenModule' },

    //Menu Wilayah
    { path: 'master-jenis-alamat-wilayah', loadChildren: './page/master/master-wilayah.module#JenisAlamatModule' },

    //Menu Pegawai
    { path: 'master-title-pegawai-pegawai', loadChildren: './page/master/master-pegawai.module#TitlePegawaiModule' },
    { path: 'master-jenis-pegawai-pegawai', loadChildren: './page/master/master-pegawai.module#JenisPegawaiModule' },
    { path: 'master-jabatan-pegawai', loadChildren: './page/master/master-pegawai.module#JabatanModule' },
    { path: 'master-pangkat-pegawai', loadChildren: './page/master/master-pegawai.module#PangkatModule' },
    { path: 'master-golonganPegawai-pegawai', loadChildren: './page/master/master-pegawai.module#GolonganPegawaiFormModule' },
    { path: 'master-kategori-pegawai-pegawai', loadChildren: './page/master/master-pegawai.module#KategoriPegawaiModule' },
    { path: 'jenis-petugas-pelaksana-pegawai', loadChildren: './page/master/master-evaluasi-pendidikan.module#JenisPetugasPelaksanaModule' },
    { path: 'master-type-pegawai-pegawai', loadChildren: './page/master/master-pegawai.module#TypePegawaiModule' },
    { path: 'master-status-pegawai', loadChildren: './page/master/master-informasi.module#StatusModule' },
    { path: 'master-status-perkawinan-pegawai', loadChildren: './page/master/master-informasi.module#StatusModule' },
    { path: 'master-pendidikan-pegawai', loadChildren: './page/master/master-evaluasi-pendidikan.module#PendidikanModule' },
    { path: 'fakultas-pegawai', loadChildren: './page/master/master-evaluasi-pendidikan.module#FakultasModule' },
    { path: 'master-kualifikasi-jurusan-pegawai', loadChildren: './page/master/master-evaluasi-pendidikan.module#KualifikasiJurusanModule' },
    { path: 'master-pekerjaan-pegawai', loadChildren: './page/master/master-pegawai.module#PekerjaanModule' },
    { path: 'master-hubungan-keluarga-pegawai', loadChildren: './page/master/master-biodata.module#HubunganKeluargaModule' },
    { path: 'hubungan-pegawai', loadChildren: './page/master/master-pegawai.module#HubunganModule' },
    { path: 'master-level-tingkat-pegawai', loadChildren: './page/master/master-khusus.module#LevelTingkatModule' },
    { path: 'jenis-organisasi-pegawai', loadChildren: './page/master/master-informasi.module#JenisOrganisasiModule' },

    { path: 'range-masakerja', loadChildren: './page/master/master-khusus.module#RangeMasaKerjaModule' },

    //Menu Penghargaan/Pelanggaran
    { path: 'master-asal-award-offence', loadChildren: './page/master/master-informasi.module#AsalModule' },
    { path: 'keterangan-alasan-award-offence', loadChildren: './page/master/master-informasi.module#KeteranganAlasanModule' },
    { path: 'kelompok-transaksi-detail-award-offence', loadChildren: './page/master/master-kelompok-transaksi.module#KelompokTransaksiDetailModule' },
    { path: 'master-award-offence', loadChildren: './page/master/master-khusus.module#AwardOffenceModule' },
    { path: 'cara-bayar-award-offence', loadChildren: './page/master/master-khusus.module#CaraBayarModule' },
    { path: 'master-jenis-dokumen-award-offence', loadChildren: './page/master/master-dokumen.module#JenisDokumenModule' },


    //Menu Fasilitas Pegawai (Perlengkapan Kerja)
    { path: 'master-jenis-aset-fasilitas-pegawai', loadChildren: './page/master/master-aset.module#JenisAsetModule' },
    { path: 'kategori-aset-fasilitas-pegawai', loadChildren: './page/master/master-aset.module#KategoriAsetModule' },
    { path: 'kelompok-aset-fasilitas-pegawai', loadChildren: './page/master/master-aset.module#kelompokasetModule' },
    { path: 'master-warna-produk-fasilitas-pegawai', loadChildren: './page/master/master-produk.module#WarnaProdukModule' },
    { path: 'bahan-produk-fasilitas-pegawai', loadChildren: './page/master/master-produk.module#BahanProdukModule' },
    { path: 'kondisi-produk-fasilitas-pegawai', loadChildren: './page/master/master-produk.module#KondisiProdukModule' },
    { path: 'master-merk-produk', loadChildren: './page/master/master-produk.module#MerkProdukModule' },
    { path: 'master-type-produk', loadChildren: './page/master/master-produk.module#TypeProdukModule' },
    { path: 'master-produsen-produk', loadChildren: './page/master/master-produk.module#ProdusenProdukModule' },
    { path: 'metode-delivery-fasilitas-pegawai', loadChildren: './page/master/master-aset.module#MetodeDeliveryModule' },
    { path: 'satuan-standar-fasilitas-pegawai', loadChildren: './page/master/master-aset.module#SatuanStandarModule' },
    { path: 'transmisi-fasilitas-pegawai', loadChildren: './page/master/master-aset.module#TransmisiModule' },
    { path: 'registrasiaset-fasilitas-pegawai', loadChildren: './page/master/master-aset.module#RegistrasiAsetModule' },
    { path: 'master-aset-fasilitas', loadChildren: './page/master/master-aset.module#MasterAsetFasilitasModule' },
    { path: 'pegawai-sk-fasilitas-new', loadChildren: './page/master/master-aset.module#PegawaiSkFasilitasNewModule' },


    //Menu Pemeriksaan Pegawai
    { path: 'master-satuan-hasil-pemeriksaan-pegawai', loadChildren: './page/master/master-informasi.module#SatuanHasilModule' },
    { path: 'komponen-pemeriksaan-pegawai', loadChildren: './page/master/master-informasi.module#KomponenModule' },
    { path: 'komponen-hasil-pemeriksaan-pegawai', loadChildren: './page/master/master-informasi.module#KomponenHasilModule' },


    { path: 'komponen-pemeriksaanobjektif', loadChildren: './page/master/master-informasi.module#KomponenPemeriksaanObjektifModule' },
    { path: 'komponen-pemeriksaanlaboratorium', loadChildren: './page/master/master-informasi.module#KomponenPemeriksaanLaboratoriumModule' },
    { path: 'komponen-penilaiankompetensi', loadChildren: './page/master/master-informasi.module#KomponenPenilaianKompetensiModule' },
    { path: 'komponen-gaji', loadChildren: './page/master/master-informasi.module#KomponenGajiModule' },
    { path: 'komponen-evaluasiorientasi', loadChildren: './page/master/master-informasi.module#KomponenEvaluasiOrientasiModule' },
    { path: 'komponen-evaluasijabatan', loadChildren: './page/master/master-informasi.module#KomponenEvaluasiJabatanModule' },

    //Menu Orientasi Pegawai
    { path: 'master-asal-anggaran-orientasi', loadChildren: './page/master/master-informasi.module#AsalModule' },
    { path: 'master-asal-peserta-orientasi', loadChildren: './page/master/master-informasi.module#AsalModule' },
    { path: 'keterangan-alasan-orientasi', loadChildren: './page/master/master-informasi.module#KeteranganAlasanModule' },
    { path: 'master-kelompok-transaksi-orientasi', loadChildren: './page/master/master-kelompok-transaksi.module#KelompokTransaksiModule' },
    { path: 'kelompok-transaksi-detail-orientasi', loadChildren: './page/master/master-kelompok-transaksi.module#KelompokTransaksiDetailModule' },
    { path: 'jenis-petugas-pelaksana-orientasi', loadChildren: './page/master/master-evaluasi-pendidikan.module#JenisPetugasPelaksanaModule' },
    { path: 'kelompok-evaluasi-orientasi', loadChildren: './page/master/master-evaluasi-pendidikan.module#KelompokEvaluasiModule' },
    { path: 'master-event-orientasi', loadChildren: './page/master/master-kalender.module#EventModule' },
    { path: 'produk-nama-orientasi', loadChildren: './page/master/master-produk.module#ProdukModule' },
    { path: 'produk-biaya-orientasi', loadChildren: './page/master/master-produk.module#ProdukModule' },
    { path: 'master-jenis-tarif-orientasi', loadChildren: './page/master/master-khusus.module#JenisTarifModule' },
    { path: 'komponen-orientasi', loadChildren: './page/master/master-informasi.module#KomponenModule' },
    { path: 'harga-netto-produk-by-kelas-orientasi', loadChildren: './page/master/master-produk.module#HargaNettoProdukBykelasModule' },


    //Menu Perjalanan Dinas
    { path: 'produk-perjalanan-dinas', loadChildren: './page/master/master-produk.module#ProdukModule' },
    { path: 'komponen-perjalanan-dinas', loadChildren: './page/master/master-informasi.module#KomponenModule' },
    { path: 'master-kelas-perjalanan-dinas', loadChildren: './page/master/master-khusus.module#KelasModule' },
    { path: 'master-jenis-tarif-perjalanan-dinas', loadChildren: './page/master/master-khusus.module#JenisTarifModule' },
    { path: 'harga-netto-produk-by-kelas-perjalanan-dinas', loadChildren: './page/master/master-produk.module#HargaNettoProdukBykelasModule' },
    { path: 'keterangan-alasan-perjalanan-dinas', loadChildren: './page/master/master-informasi.module#KeteranganAlasanModule' },
    { path: 'master-kelompok-transaksi-perjalanan-dinas', loadChildren: './page/master/master-kelompok-transaksi.module#KelompokTransaksiModule' },
    { path: 'kelompok-transaksi-detail-perjalanan-dinas', loadChildren: './page/master/master-kelompok-transaksi.module#KelompokTransaksiDetailModule' },
    { path: 'master-jenis-dokumen-perjalanan-dinas', loadChildren: './page/master/master-dokumen.module#JenisDokumenModule' },

    //Menu Jadwal
    { path: 'master-harilibur-jadwal', loadChildren: './page/master/master-kalender.module#HariLiburModule' },
    { path: 'kelompok-shift-kerja-jadwal', loadChildren: './page/master/master-jadwal.module#KelompokShiftKerjaModule' },
    { path: 'shift-kerja-jadwal', loadChildren: './page/master/master-jadwal.module#ShiftKerjaModule' },
    { path: 'shift-kerja-formulasi-jadwal', loadChildren: './page/master/master-jadwal.module#ShiftKerjaFormulasiModule' },

    //Menu Cuti Pegawai
    { path: 'keterangan-alasan-cuti', loadChildren: './page/master/master-informasi.module#KeteranganAlasanModule' },
    { path: 'master-kelompok-transaksi-cuti', loadChildren: './page/master/master-kelompok-transaksi.module#KelompokTransaksiModule' },
    { path: 'kelompok-transaksi-detail-cuti', loadChildren: './page/master/master-kelompok-transaksi.module#KelompokTransaksiDetailModule' },
    { path: 'master-status-cuti', loadChildren: './page/master/master-informasi.module#StatusModule' },
    { path: 'range-cuti', loadChildren: './page/master/master-khusus.module#RangeModule' },
    { path: 'master-jenis-dokumen-cuti', loadChildren: './page/master/master-dokumen.module#JenisDokumenModule' },


    { path: 'range-masakerja-cuti', loadChildren: './page/master/master-khusus.module#RangeMasaKerjaCutiModule' },
    { path: 'range-keterlambatan', loadChildren: './page/master/master-khusus.module#RangeKeterlambatanModule' },
    { path: 'range-liburharioff-liburnasional', loadChildren: './page/master/master-khusus.module#RangeLiburHariOffLiburNasionalModule' },
    { path: 'range-liburharikerjanormal', loadChildren: './page/master/master-khusus.module#RangeLiburHariKerjaNormalModule' },

    //Menu Lembur
    { path: 'keterangan-alasan-lembur', loadChildren: './page/master/master-informasi.module#KeteranganAlasanModule' },
    { path: 'master-kelompok-transaksi-lembur', loadChildren: './page/master/master-kelompok-transaksi.module#KelompokTransaksiModule' },
    { path: 'kelompok-transaksi-detail-lembur', loadChildren: './page/master/master-kelompok-transaksi.module#KelompokTransaksiDetailModule' },
    { path: 'range-lembur', loadChildren: './page/master/master-khusus.module#RangeModule' },
    { path: 'master-status-lembur', loadChildren: './page/master/master-informasi.module#StatusModule' },
    { path: 'master-jenis-dokumen-lembur', loadChildren: './page/master/master-dokumen.module#JenisDokumenModule' },

    //Menu Resign
    { path: 'keterangan-alasan-resign', loadChildren: './page/master/master-informasi.module#KeteranganAlasanModule' },
    { path: 'master-kelompok-transaksi-resign', loadChildren: './page/master/master-kelompok-transaksi.module#KelompokTransaksiModule' },
    { path: 'kelompok-transaksi-detail-resign', loadChildren: './page/master/master-kelompok-transaksi.module#KelompokTransaksiDetailModule' },
    { path: 'master-status-resign', loadChildren: './page/master/master-informasi.module#StatusModule' },
    { path: 'master-jenis-dokumen-resign', loadChildren: './page/master/master-dokumen.module#JenisDokumenModule' },

    //Menu Pinjaman
    { path: 'keterangan-alasan-pinjaman', loadChildren: './page/master/master-informasi.module#KeteranganAlasanModule' },
    { path: 'master-kelompok-transaksi-pinjaman', loadChildren: './page/master/master-kelompok-transaksi.module#KelompokTransaksiModule' },
    { path: 'kelompok-transaksi-detail-pinjaman', loadChildren: './page/master/master-kelompok-transaksi.module#KelompokTransaksiDetailModule' },
    { path: 'jenis-bunga-pinjaman', loadChildren: './page/master/master-pinjaman.module#JenisBungaModule' },
    { path: 'jenis-suku-bunga-pinjaman', loadChildren: './page/master/master-pinjaman.module#JenisSukuBungaModule' },
    { path: 'metode-perhitungan-pinjaman', loadChildren: './page/master/master-pinjaman.module#MetodePerhitunganModule' },
    { path: 'metode-pembayaran-pinjaman', loadChildren: './page/master/master-pinjaman.module#MetodePembayaranModule' },
    { path: 'cara-bayar-pinjaman', loadChildren: './page/master/master-khusus.module#CaraBayarModule' },
    { path: 'produk-pinjaman', loadChildren: './page/master/master-produk.module#ProdukModule' },
    { path: 'master-jenis-dokumen-pinjaman', loadChildren: './page/master/master-dokumen.module#JenisDokumenModule' },

    { path: 'range-waktupinjaman', loadChildren: './page/master/master-khusus.module#RangeWaktuPinjamanModule' },
    { path: 'range-pinjaman', loadChildren: './page/master/master-khusus.module#RangePinjamanModule' },
    { path: 'range-masakerja-pinjaman', loadChildren: './page/master/master-khusus.module#RangeMasaKerjaPinjamanModule' },

    //Menu Reimburs
    { path: 'keterangan-alasan-reimburs', loadChildren: './page/master/master-informasi.module#KeteranganAlasanModule' },
    { path: 'master-kelompok-transaksi-reimburs', loadChildren: './page/master/master-kelompok-transaksi.module#KelompokTransaksiModule' },
    { path: 'kelompok-transaksi-detail-reimburs', loadChildren: './page/master/master-kelompok-transaksi.module#KelompokTransaksiDetailModule' },
    { path: 'jenis-transaksi-reimburs', loadChildren: './page/master/master-aset.module#JenisTransaksiModule' },
    { path: 'paket-reimburs', loadChildren: './page/master/master-aset.module#PaketModule' },
    { path: 'produk-reimburs', loadChildren: './page/master/master-produk.module#ProdukModule' },
    { path: 'master-jenis-dokumen-reimburs', loadChildren: './page/master/master-dokumen.module#JenisDokumenModule' },


    { path: 'range-masakerja-reimburs', loadChildren: './page/master/master-khusus.module#RangeMasaKerjaReimbursModule' },

    //Menu Reimburs Perjalanan Dinas
    { path: 'keterangan-alasan-reimburs-perjalanan-dinas', loadChildren: './page/master/master-informasi.module#KeteranganAlasanModule' },
    { path: 'master-kelompok-transaksi-reimburs-perjalanan-dinas', loadChildren: './page/master/master-kelompok-transaksi.module#KelompokTransaksiModule' },
    { path: 'kelompok-transaksi-detail-reimburs-perjalanan-dinas', loadChildren: './page/master/master-kelompok-transaksi.module#KelompokTransaksiDetailModule' },
    { path: 'jenis-transaksi-reimburs-perjalanan-dinas', loadChildren: './page/master/master-aset.module#JenisTransaksiModule' },
    { path: 'paket-reimburs-perjalanan-dinas', loadChildren: './page/master/master-aset.module#PaketModule' },
    { path: 'produk-reimburs-perjalanan-dinas', loadChildren: './page/master/master-produk.module#ProdukModule' },
    { path: 'master-kelas-reimburs-perjalanan-dinas', loadChildren: './page/master/master-khusus.module#KelasModule' },
    { path: 'harga-netto-produk-by-kelas-reimburs-perjalanan-dinas', loadChildren: './page/master/master-produk.module#HargaNettoProdukBykelasModule' },
    { path: 'master-jenis-dokumen-reimburs-perjalanan-dinas', loadChildren: './page/master/master-dokumen.module#JenisDokumenModule' },
    //Menu Evaluasi Jabatan
    { path: 'master-jenis-waktu-evaluasi', loadChildren: './page/master/master-kalender.module#JenisWaktuModule' },
    { path: 'keterangan-alasan-evaluasi', loadChildren: './page/master/master-informasi.module#KeteranganAlasanModule' },
    { path: 'master-kelompok-transaksi-evaluasi', loadChildren: './page/master/master-kelompok-transaksi.module#KelompokTransaksiModule' },
    { path: 'kelompok-transaksi-detail-evaluasi', loadChildren: './page/master/master-kelompok-transaksi.module#KelompokTransaksiDetailModule' },
    { path: 'type-data-object-evaluasi', loadChildren: './page/master/master-aplikasi.module#TypeDataObjectModule' },
    { path: 'kelompok-evaluasi-evaluasi', loadChildren: './page/master/master-evaluasi-pendidikan.module#KelompokEvaluasiModule' },
    { path: 'komponen-evaluasi', loadChildren: './page/master/master-informasi.module#KomponenModule' },
    { path: 'master-jenis-dokumen-evaluasi', loadChildren: './page/master/master-dokumen.module#JenisDokumenModule' },

    //Menu PHK
    { path: 'keterangan-alasan-phk', loadChildren: './page/master/master-informasi.module#KeteranganAlasanModule' },
    { path: 'master-kelompok-transaksi-phk', loadChildren: './page/master/master-kelompok-transaksi.module#KelompokTransaksiModule' },
    { path: 'kelompok-transaksi-detail-phk', loadChildren: './page/master/master-kelompok-transaksi.module#KelompokTransaksiDetailModule' },
    { path: 'master-jenis-dokumen-phk', loadChildren: './page/master/master-dokumen.module#JenisDokumenModule' },
    { path: 'status-phk', loadChildren: './page/master/master-informasi.module#StatusModule' },
    { path: 'profile-struktur-gaji-by-mkgp-phk', loadChildren: './page/master/master-profile.module#ProfileStrukturGajiByMkgpModule' },


    { path: 'range-masakerja-phk', loadChildren: './page/master/master-khusus.module#RangeMasaKerjaPhkModule' },

    //Menu Asuransi
    { path: 'master-rekanan-asuransi', loadChildren: './page/master/master-asuransi.module#RekananModule' },
    { path: 'master-hubungan-peserta-asuransi-asuransi', loadChildren: './page/master/master-asuransi.module#HubunganPesertaAsuransiModule' },
    { path: 'golongan-asuransi', loadChildren: './page/master/master-asuransi.module#GolonganAsuransiModule' },

    //Menu Pajak
    { path: 'master-penghasilan-tidak-kena-pajak-pajak', loadChildren: './page/master/master-pajak.module#PenghasilanTidakKenaPajakModule' },
    { path: 'produk-pajak', loadChildren: './page/master/master-produk.module#ProdukModule' },
    { path: 'komponen-pajak', loadChildren: './page/master/master-informasi.module#KomponenModule' },
    { path: 'pajak-pajak', loadChildren: './page/master/master-pajak.module#PajakModule' },
    { path: 'objek-pajak-pajak', loadChildren: './page/master/master-pajak.module#ObjekPajakModule' },

    //Menu Penggajian
    { path: 'periode-penggajian', loadChildren: './page/master/master-kalender.module#PeriodeModule' },
    { path: 'range-penggajian', loadChildren: './page/master/master-khusus.module#RangeModule' },
    { path: 'produk-penggajian', loadChildren: './page/master/master-produk.module#ProdukModule' },
    { path: 'komponen-penggajian', loadChildren: './page/master/master-informasi.module#KomponenModule' },
    { path: 'profile-struktur-gaji-by-mkgp-penggajian', loadChildren: './page/master/master-profile.module#ProfileStrukturGajiByMkgpModule' },

    //Menu THR
    { path: 'periode-thr', loadChildren: './page/master/master-kalender.module#PeriodeModule' },
    { path: 'range-thr', loadChildren: './page/master/master-khusus.module#RangeModule' },
    { path: 'produk-thr', loadChildren: './page/master/master-produk.module#ProdukModule' },
    { path: 'komponen-thr', loadChildren: './page/master/master-informasi.module#KomponenModule' },
    { path: 'profile-struktur-gaji-by-mkgp-thr', loadChildren: './page/master/master-profile.module#ProfileStrukturGajiByMkgpModule' },

    { path: 'range-masakerja-thr', loadChildren: './page/master/master-khusus.module#RangeMasaKerjaThrModule' },

    //Menu Bonus
    { path: 'periode-bonus', loadChildren: './page/master/master-kalender.module#PeriodeModule' },
    { path: 'range-bonus', loadChildren: './page/master/master-khusus.module#RangeModule' },
    { path: 'produk-bonus', loadChildren: './page/master/master-produk.module#ProdukModule' },
    { path: 'komponen-bonus', loadChildren: './page/master/master-informasi.module#KomponenModule' },
    { path: 'profile-struktur-gaji-by-mkgp-bonus', loadChildren: './page/master/master-profile.module#ProfileStrukturGajiByMkgpModule' },

    //Menu Pensiun
    { path: 'keterangan-alasan-pensiun', loadChildren: './page/master/master-informasi.module#KeteranganAlasanModule' },
    { path: 'kelompok-transaksi-detail-pensiun', loadChildren: './page/master/master-kelompok-transaksi.module#KelompokTransaksiDetailModule' },
    { path: 'master-jenis-dokumen-pensiun', loadChildren: './page/master/master-dokumen.module#JenisDokumenModule' },


    { path: 'range-masakerja-pensiun', loadChildren: './page/master/master-khusus.module#RangeMasaKerjaPensiunModule' },
    { path: 'range-masakerja-kategori', loadChildren: './page/master/master-khusus.module#RangeMasaKerjaKategoriModule' },


    { path: 'cek-pinjaman-pegawai-berhenti', loadChildren: './page/master/master-pegawai-sk.module#CekPinjamanPegawaiBerhentiModule' },

    //Menu Pesangon
    { path: 'periode-pesangon', loadChildren: './page/master/master-kalender.module#PeriodeModule' },
    { path: 'range-pesangon', loadChildren: './page/master/master-khusus.module#RangeModule' },
    { path: 'produk-pesangon', loadChildren: './page/master/master-produk.module#ProdukModule' },
    { path: 'komponen-pesangon', loadChildren: './page/master/master-informasi.module#KomponenModule' },
    { path: 'profile-struktur-gaji-by-mkgp-pesangon', loadChildren: './page/master/master-profile.module#ProfileStrukturGajiByMkgpModule' },

    //Menu Setting Data Fixed
    { path: 'master-settingdatafixed', loadChildren: './page/master/master-aplikasi.module#SettingDataFixedModule' },

    //Menu Sistem Administrator
    { path: 'master-modul-aplikasi-sisadmin', loadChildren: './page/master/master-aplikasi.module#ModulAplikasiModule' },
    { path: 'master-kelompok-transaksi-sisadmin', loadChildren: './page/master/master-kelompok-transaksi.module#KelompokTransaksiModule' },
    { path: 'type-data-object-sisadmin', loadChildren: './page/master/master-aplikasi.module#TypeDataObjectModule' },
    { path: 'master-objek-modul-aplikasi-sisadmin', loadChildren: './page/master/master-aplikasi.module#ObjekModulAplikasiModule' },
    { path: 'master-negara-sisadmin', loadChildren: './page/master/master-wilayah.module#NegaraModule' },
    { path: 'master-matauang-sisadmin', loadChildren: './page/master/master-khusus.module#MatauangModule' },
    { path: 'master-propinsi-sisadmin', loadChildren: './page/master/master-wilayah.module#PropinsiModule' },
    { path: 'master-kota-kabupaten-sisadmin', loadChildren: './page/master/master-wilayah.module#KotakabupatenModule' },
    { path: 'master-kecamatan-sisadmin', loadChildren: './page/master/master-wilayah.module#KecamatanModule' },
    { path: 'master-desaKelurahan-sisadmin', loadChildren: './page/master/master-wilayah.module#DesaKelurahanModule' },
    { path: 'master-hari-sisadmin', loadChildren: './page/master/master-kalender.module#HariFormModule' },
    { path: 'master-jenis-anggaran', loadChildren: './page/master/master-data.module#JenisAnggaranModule' },
    { path: 'master-bulan-sisadmin', loadChildren: './page/master/master-kalender.module#BulanModule' },
    { path: 'master-kalender-sisadmin', loadChildren: './page/master/master-kalender.module#KalenderModule' },
    { path: 'master-bahasa-sisadmin', loadChildren: './page/master/master-biodata.module#BahasaModule' },
    { path: 'master-jenis-kelamin-sisadmin', loadChildren: './page/master/master-biodata.module#JenisKelaminModule' },
    { path: 'master-golonganDarah-sisadmin', loadChildren: './page/master/master-biodata.module#GolonganDarahFormModule' },
    { path: 'master-agama-sisadmin', loadChildren: './page/master/master-biodata.module#AgamaModule' },
    { path: 'master-suku-sisadmin', loadChildren: './page/master/master-biodata.module#SukuModule' },
    { path: 'master-produsen-produk-sisadmin', loadChildren: './page/master/master-produk.module#ProdusenProdukModule' },
    { path: 'master-merk-produk-sisadmin', loadChildren: './page/master/master-produk.module#MerkProdukModule' },
    { path: 'master-type-produk-sisadmin', loadChildren: './page/master/master-produk.module#TypeProdukModule' },
    { path: 'master-shio-unsur-sisadmin', loadChildren: './page/master/master-biodata.module#ZodiakUnsurModule' },
    { path: 'master-shio-sisadmin', loadChildren: './page/master/master-biodata.module#ZodiakModule' },
    { path: 'master-shio-unsur-range-sisadmin', loadChildren: './page/master/master-biodata.module#ZodiakUnsurRangeModule' },
    { path: 'master-histori-login-user-sisadmin', loadChildren: './page/master/master-aplikasi.module#HistoriLoginUserModule' },
    { path: 'login-user-sisadmin', loadChildren: './page/master/master-aplikasi.module#LoginUserModule' },
    { path: 'master-messaging-sisadmin', loadChildren: './page/master/master-aplikasi.module#MessagingModule' },
    { path: 'master-kelompok-user', loadChildren: './page/master/master-aplikasi.module#KelompokUserModule' },
    // 

    //master baru
    { path: 'master-penyebab-kematian', loadChildren: './page/master/master-khusus.module#PenyebabKematianModule' },
    { path: 'master-report-jumlah-keterlambatan', loadChildren: './page/master/master-khusus.module#ReportJumlahKeterlambatanKaryawanModule' },
    { path: 'master-kelompok-status', loadChildren: './page/master/master-informasi.module#KelompokStatusModule' },
    { path: 'master-program', loadChildren: './page/master/master-data.module#ProgramModule' },
    { path: 'master-jenis-anggaran', loadChildren: './page/master/master-data.module#JenisAnggaranModule' },
    { path: 'master-jenis-jurnal', loadChildren: './page/master/master-data.module#JenisJurnalModule' },
    { path: 'master-map-ruangan-jurusan', loadChildren: './page/master/master-data.module#MapRuanganJurusanModule' },
    { path: 'master-fasilitas-ruangan', loadChildren: './page/master/master-data.module#MapFasilitasRuanganModule' },
    { path: 'master-map-fakultas-program', loadChildren: './page/master/master-data.module#MapFakultasToProgramModule' },
    { path: 'master-map-fakultas-program-jurusan', loadChildren: './page/master/master-data.module#MapFakultasProgramJurusanModule' },
    { path: 'master-new-dokumen', loadChildren: './page/master/master-data.module#MasterNewDokumenModule' },
    { path: 'master-kasus-penyakit', loadChildren: './page/master/master-data.module#KasusPenyakitModule' },
    { path: 'master-penyebab-infeksi-nosokomial', loadChildren: './page/master/master-data.module#PenyebabInfeksiNosokomialModule' },
    { path: 'master-penyebab-diagnosa', loadChildren: './page/master/master-data.module#PenyebabDiagnosaModule' },
    { path: 'map-komputer-to-printer', loadChildren: './page/master/master-profile.module#MapKomputerToPrinterModule' },

    { path: 'master-pelayanan-profile', loadChildren: './page/master/master-data.module#PelayananProfileModule' },
    { path: 'master-manual-help', loadChildren: './page/master/master-data.module#ManualHelpModule' },
    { path: 'master-input-berita', loadChildren: './page/master/master-data.module#InputBeritaModule' },
    { path: 'master-profilehistoryevent', loadChildren: './page/master/master-data.module#ProfileHistoryEventModule' },
    { path: 'master-loginuserconfigss', loadChildren: './page/master/master-data.module#LoginUserConfigSSModule' },
    { path: 'master-design-config', loadChildren: './page/master/master-data.module#DesignConfigurationModule' },
    { path: 'master-manual-help', loadChildren: './page/master/master-data.module#ManualHelpModule' },
    { path: 'master-modul-aplikasi-help', loadChildren: './page/master/master-data.module#ModulAplikasiHelpModule' },
    { path: 'master-modul-aplikasi-histori', loadChildren: './page/master/master-data.module#ModulAplikasiHistoriModule' },
    { path: 'master-kelompok-penyebab-diagnosa', loadChildren: './page/master/master-data.module#KelompokPenyebabDiagnosaModule' },
    { path: 'master-mekanisme-interaksi-produk', loadChildren: './page/master/master-data.module#MekanismeInteraksiProdukModule' },
    { path: 'master-type', loadChildren: './page/master/master-data.module#MasterTypeModule' },
    { path: 'master-harga-paket-penjamin', loadChildren: './page/master/master-data.module#HargaPaketPenjaminModule' },
    { path: 'master-jenis-komponen', loadChildren: './page/master/master-data.module#JenisKomponenModule' },
    { path: 'master-jenis-kontak', loadChildren: './page/master/master-data.module#JenisKontakModule' },
    { path: 'master-jenis-klaim', loadChildren: './page/master/master-data.module#JenisKlaimModule' },
    { path: 'master-interaksi-produk', loadChildren: './page/master/master-data.module#InteraksiProdukModule' },
    { path: 'master-title-pasien', loadChildren: './page/master/master-data.module#MasterTitlePasienModule' },
    { path: 'master-kelompok-umur', loadChildren: './page/master/master-data.module#KelompokUmurModule' },
    { path: 'master-title', loadChildren: './page/master/master-data.module#MasterTitleModule' },
    { path: 'map-title-status-perkawinan', loadChildren: './page/master/master-data.module#MapTitleToStatusPerkawinanModule' },
    { path: 'master-visi', loadChildren: './page/master/master-data.module#MasterVisiModule' },
    { path: 'master-misi', loadChildren: './page/master/master-data.module#MasterMisiModule' },
    { path: 'sejarah-profile', loadChildren: './page/master/master-data.module#SejarahProfileModule' },
    { path: 'visi-misi-perusahaan', loadChildren: './page/master/master-data.module#VisiMisiPerusahaanModule' },
    { path: 'language-manager', loadChildren: './page/master/master-data.module#LanguageManagerModule' },
    { path: 'master-modul-aplikasi-language', loadChildren: './page/master/master-data.module#ModulAplikasiLanguageModule' },
    { path: 'master-profile-konfigurasi-design', loadChildren: './page/master/master-data.module#ProfileKonfigurasiDesignModule' },

    { path: 'master-penyebab-kematian', loadChildren : './page/master/master-khusus.module#PenyebabKematianModule' },
    { path: 'master-report-jumlah-keterlambatan', loadChildren : './page/master/master-khusus.module#ReportJumlahKeterlambatanKaryawanModule' },
    { path: 'master-kelompok-status', loadChildren : './page/master/master-informasi.module#KelompokStatusModule' },
    { path: 'master-program', loadChildren : './page/master/master-data.module#ProgramModule' },
    { path: 'master-jenis-anggaran', loadChildren : './page/master/master-data.module#JenisAnggaranModule' },
    { path: 'master-jenis-jurnal', loadChildren : './page/master/master-data.module#JenisJurnalModule' },
    { path: 'master-map-ruangan-jurusan', loadChildren : './page/master/master-data.module#MapRuanganJurusanModule' },
    { path: 'master-fasilitas-ruangan', loadChildren : './page/master/master-data.module#MapFasilitasRuanganModule'},
    { path: 'master-map-fakultas-program', loadChildren: './page/master/master-data.module#MapFakultasToProgramModule'},
    { path: 'master-map-fakultas-program-jurusan', loadChildren: './page/master/master-data.module#MapFakultasProgramJurusanModule'},
    { path: 'master-new-dokumen', loadChildren: './page/master/master-data.module#MasterNewDokumenModule'},
    { path: 'master-kasus-penyakit', loadChildren: './page/master/master-data.module#KasusPenyakitModule'},
    { path: 'master-penyebab-infeksi-nosokomial', loadChildren: './page/master/master-data.module#PenyebabInfeksiNosokomialModule'},
    { path: 'master-penyebab-diagnosa', loadChildren: './page/master/master-data.module#PenyebabDiagnosaModule'},
    { path: 'map-komputer-to-printer', loadChildren: './page/master/master-profile.module#MapKomputerToPrinterModule'},

    { path: 'master-pelayanan-profile', loadChildren: './page/master/master-data.module#PelayananProfileModule'},
    { path: 'master-manual-help', loadChildren: './page/master/master-data.module#ManualHelpModule'},
    { path: 'master-input-berita', loadChildren: './page/master/master-data.module#InputBeritaModule'},
    { path: 'master-profilehistoryevent', loadChildren: './page/master/master-data.module#ProfileHistoryEventModule'},
    { path: 'master-loginuserconfigss', loadChildren: './page/master/master-data.module#LoginUserConfigSSModule'},
    { path: 'master-design-config', loadChildren: './page/master/master-data.module#DesignConfigurationModule'},
    { path: 'master-manual-help', loadChildren: './page/master/master-data.module#ManualHelpModule'},
    { path: 'master-modul-aplikasi-help', loadChildren: './page/master/master-data.module#ModulAplikasiHelpModule'},
    { path: 'master-modul-aplikasi-histori', loadChildren: './page/master/master-data.module#ModulAplikasiHistoriModule'},
    { path: 'master-kelompok-penyebab-diagnosa', loadChildren: './page/master/master-data.module#KelompokPenyebabDiagnosaModule'},
    { path: 'master-mekanisme-interaksi-produk', loadChildren: './page/master/master-data.module#MekanismeInteraksiProdukModule'},
    { path: 'master-type', loadChildren: './page/master/master-data.module#MasterTypeModule'},
    { path: 'master-harga-paket-penjamin', loadChildren: './page/master/master-data.module#HargaPaketPenjaminModule'},
    { path: 'master-jenis-komponen', loadChildren: './page/master/master-data.module#JenisKomponenModule'},
    { path: 'master-jenis-kontak', loadChildren: './page/master/master-data.module#JenisKontakModule'},
    { path: 'master-jenis-klaim', loadChildren: './page/master/master-data.module#JenisKlaimModule'},
    { path: 'master-interaksi-produk', loadChildren: './page/master/master-data.module#InteraksiProdukModule'},
    { path: 'master-title-pasien', loadChildren: './page/master/master-data.module#MasterTitlePasienModule'},
    { path: 'master-kelompok-umur', loadChildren: './page/master/master-data.module#KelompokUmurModule'},
    { path: 'master-title', loadChildren: './page/master/master-data.module#MasterTitleModule'},
    { path: 'map-title-status-perkawinan', loadChildren: './page/master/master-data.module#MapTitleToStatusPerkawinanModule'},
    { path: 'master-visi', loadChildren: './page/master/master-data.module#MasterVisiModule'},
    { path: 'master-misi', loadChildren: './page/master/master-data.module#MasterMisiModule'},
    { path: 'sejarah-profile', loadChildren: './page/master/master-data.module#SejarahProfileModule'},
    { path: 'histori-tujuan', loadChildren: './page/master/master-data.module#HistoriTujuanModule'},
    { path: 'master-rekanan', loadChildren: './page/master/master-data.module#MasterRekananModule'},
    { path: 'visi-misi-perusahaan', loadChildren: './page/master/master-data.module#VisiMisiPerusahaanModule'},
    { path: 'master-prosedur-pelayanan', loadChildren: './page/master/master-data.module#MasterProsedurPelayananModule'},
    { path: 'master-harga-paket-pelayanan', loadChildren: './page/master/master-data.module#HargaPaketPelayananModule' },
    { path: 'map-ruangan-to-kelas', loadChildren : './page/master/master-data.module#MapRuanganToKelasModule' },
    { path: 'jenis-respon', loadChildren : './page/master/master-data.module#JenisResponModule' },
    { path: 'monitoring-customer-care', loadChildren : './page/master/master-data.module#MonitoringCustomerCareModule' },
    { path: 'monitoring-user-baru', loadChildren : './page/master/master-data.module#MonitoringUserBaruModule' },
    { path: 'monitoring-subscribe', loadChildren : './page/master/master-data.module#MonitoringSubscribeModule' },
    { path: 'map-paketmodulaplikasi-to-objekmodul', loadChildren : './page/master/master-data.module#MapPaketModulAplikasiToObjekModulModule' },
    { path: 'master-blog', loadChildren : './page/master/master-data.module#BlogModule' },
    { path: 'map-paket-modul-aplikasi-to-produk', loadChildren : './page/master/master-data.module#MapPaketModulAplikasiToProdukModule' },
    
    //miftah
    { path: 'komponen-msa', loadChildren : './page/master/master-informasi.module#KomponenMsaModule' },
    { path: 'jadwal-dokter', loadChildren : './page/master/master-data.module#JadwalDokterModule' },
    
    //Menu KPI
    { path: 'master-visi-kpi', loadChildren: './page/master/master-informasi.module#VisiModule' },
    { path: 'master-misi-kpi', loadChildren: './page/master/master-informasi.module#MisiModule' },
    { path: 'master-jenis-dokumen-kpi', loadChildren: './page/master/master-dokumen.module#JenisDokumenModule' },
    { path: 'jenis-deskripsi-kpi', loadChildren: './page/master/master-informasi.module#JenisDeskripsiModule' },
    { path: 'deskripsi-kpi', loadChildren: './page/master/master-informasi.module#DeskripsiModule' },
    { path: 'master-kategori-deskripsi-kpi', loadChildren: './page/master/master-informasi.module#KategoriDeskripsiModule' },
    { path: 'master-spesifikasi-kpi', loadChildren: './page/master/master-kpi.module#SpesifikasiModule' },
    { path: 'master-perspective-kpi', loadChildren: './page/master/master-kpi.module#PerspectiveModule' },
    { path: 'master-kpi-kpi', loadChildren: './page/master/master-kpi.module#KpiModule' },
    { path: 'master-dashboard-monitoring-bsc', loadChildren: './page/master/master-kpi.module#DashboardMonitoringBscModule' },
    { path: 'master-kpi-departemen', loadChildren: './page/master/master-kpi.module#KpiDepartemenModule' },
    { path: 'bsc', loadChildren: './page/master/master-kpi.module#BscModule' },
    { path: 'monitoring-kpi', loadChildren: './page/master/master-kpi.module#MonitoringKpiModule' },
    { path: 'balance-scorecard', loadChildren: './page/master/master-kpi.module#BscModule' },
    { path: 'master-strategy', loadChildren: './page/master/master-kpi.module#StrategyModule' },
    { path: 'master-profile-histori-visi-misi', loadChildren: './page/master/master-kpi.module#ProfileHistoriVisiMisiModule' },
    { path: 'profile-histori-stms', loadChildren: './page/master/master-profile.module#ProfileHistoriStmsModule' },

    { path: 'master-alergi', loadChildren: './page/master/master-data.module#AlergiModule' },
    { path: 'master-askepintervensi', loadChildren: './page/master/master-data.module#AsKepIntervensiModule' },
    { path: 'master-askepjeniskajian', loadChildren: './page/master/master-data.module#AsKepJenisKajianModule' },
    { path: 'master-askepkategorykajian', loadChildren: './page/master/master-data.module#AsKepKategoryKajianModule' },
    { path: 'master-askepkajian', loadChildren: './page/master/master-data.module#AsKepKajianModule' },
    { path: 'master-askeprasionali', loadChildren: './page/master/master-data.module#AsKepRasionalIModule' },
    { path: 'master-askeptujuan', loadChildren: './page/master/master-data.module#AsKepTujuanModule' },
    { path: 'master-bentuk', loadChildren: './page/master/master-data.module#BentukModule' },
    { path: 'master-caralahirbayi', loadChildren: './page/master/master-data.module#CaraLahirBayiModule' },
    { path: 'master-caramasuk', loadChildren: './page/master/master-data.module#CaraMasukModule' },
    { path: 'master-jenisaccount', loadChildren: './page/master/master-data.module#JenisAccountModule' },
    { path: 'master-kategoryaccount', loadChildren: './page/master/master-data.module#KategoryAccountModule' },
    { path: 'master-chartofaccount', loadChildren: './page/master/master-data.module#ChartOfAccountModule' },
    { path: 'master-design', loadChildren: './page/master/master-data.module#DesignModule' },
    { path: 'master-kategorydiagnosa', loadChildren: './page/master/master-data.module#KategoryDiagnosaModule' },
    { path: 'master-diagnosa', loadChildren: './page/master/master-data.module#DiagnosaModule' },
    { path: 'master-diagnosakeperawatan', loadChildren: './page/master/master-data.module#DiagnosaKeperawatanModule' },
    { path: 'master-diagnosatindakan', loadChildren: './page/master/master-data.module#DiagnosaTindakanModule' },
    { path: 'master-freqaskquestions', loadChildren: './page/master/master-data.module#FreqAskQuestionsModule' },
    { path: 'master-edisi', loadChildren: './page/master/master-data.module#EdisiModule' },
    { path: 'master-eselon', loadChildren: './page/master/master-data.module#EselonModule' },
    { path: 'master-detailgolonganproduk', loadChildren: './page/master/master-data.module#DetailGolonganProdukModule' },
    { path: 'master-generalkelompokproduk', loadChildren: './page/master/master-data.module#GeneralKelompokProdukModule' },
    { path: 'master-generaljenisproduk', loadChildren: './page/master/master-data.module#GeneralJenisProdukModule' },
    { path: 'master-generalproduk', loadChildren: './page/master/master-data.module#GeneralProdukModule' },
    { path: 'master-fungsi', loadChildren: './page/master/master-data.module#FungsiModule' },
    { path: 'master-golonganproduk', loadChildren: './page/master/master-data.module#GolonganProdukModule' },
    { path: 'master-imunisasi', loadChildren: './page/master/master-data.module#ImunisasiModule' },
    { path: 'master-indikatoraccount', loadChildren: './page/master/master-data.module#IndikatorAccountModule' },
    { path: 'master-harga-netto-disc-pasien', loadChildren: './page/master/master-data.module#HargaNettoDiscPasienPulangModule' },
    { path: 'master-hargapaketmodulaplikasi', loadChildren: './page/master/master-data.module#HargaPaketModulAplikasiModule' },
    { path: 'master-kelompokklien', loadChildren: './page/master/master-data.module#KelompokKlienModule' },
    { path: 'master-version', loadChildren: './page/master/master-data.module#VersionModule' },
    { path: 'master-jenisinfeksinosokomial', loadChildren: './page/master/master-data.module#JenisInfeksiNosokomialModule' },
    { path: 'master-jenisdiagnosa', loadChildren: './page/master/master-data.module#JenisDiagnosaModule' },
    { path: 'master-jenisdiet', loadChildren: './page/master/master-data.module#JenisDietModule' },
    { path: 'master-jeniskartu', loadChildren: './page/master/master-data.module#JenisKartuModule' },
    { path: 'master-infeksi-nosokomial', loadChildren: './page/master/master-data.module#InfeksiNosokomialModule' },
    { path: 'master-jeniskemasan', loadChildren: './page/master/master-data.module#JenisKemasanModule' },
    { path: 'master-fasilitas', loadChildren: './page/master/master-data.module#FasilitasModule' },
    { path: 'master-fasilitas-detail', loadChildren: './page/master/master-data.module#FasilitasDetailModule' },
    { path: 'master-fasilitas-bed', loadChildren: './page/master/master-data.module#FasilitasBedModule' },

    { path: 'master-akun-bank', loadChildren: './page/master/master-data.module#MasterAkunBankModule' },
    { path: 'master-diskon', loadChildren: './page/master/master-data.module#MasterDiskonModule' },
];
