export const routeMasterMap = [
    { path: 'map-kelompoktransaksi-to-keteranganalasan-award-offence', loadChildren : './page/master/master-kelompok-transaksi.module#MapKelompoktransaksiKeteranganalasanModule' },
    { path: 'map-kelompoktransaksi-to-posting-award-offence', loadChildren : './page/master/master-kelompok-transaksi.module#MapKelompoktransaksiPostingModule' },
    { path: 'map-kelompoktransaksi-to-strukturnomor-award-offence', loadChildren : './page/master/master-kelompok-transaksi.module#MapKelompoktransaksiStrukturnomorModule' },
    { path: 'map-kelompoktransaksi-to-jenisdokumen-award-offence', loadChildren : './page/master/master-kelompok-transaksi.module#MapKelompoktransaksiJenisdokumenModule' },
    { path: 'map-kelompoktransaksi-to-keteranganalasan-orientasi', loadChildren : './page/master/master-kelompok-transaksi.module#MapKelompoktransaksiKeteranganalasanModule' },
    { path: 'map-kelompoktransaksi-to-posting-orientasi', loadChildren : './page/master/master-kelompok-transaksi.module#MapKelompoktransaksiPostingModule' },
    { path: 'map-kelompoktransaksi-to-strukturnomor-orientasi', loadChildren : './page/master/master-kelompok-transaksi.module#MapKelompoktransaksiStrukturnomorModule' },
    { path: 'map-kelompoktransaksi-to-keteranganalasan-perjalanan-dinas', loadChildren : './page/master/master-kelompok-transaksi.module#MapKelompoktransaksiKeteranganalasanModule' },
    { path: 'map-kelompoktransaksi-to-posting-perjalanan-dinas', loadChildren : './page/master/master-kelompok-transaksi.module#MapKelompoktransaksiPostingModule' },
    { path: 'map-kelompoktransaksi-to-strukturnomor-perjalanan-dinas', loadChildren : './page/master/master-kelompok-transaksi.module#MapKelompoktransaksiStrukturnomorModule' },
    { path: 'map-kelompoktransaksi-to-jenisdokumen-perjalanan-dinas', loadChildren : './page/master/master-kelompok-transaksi.module#MapKelompoktransaksiJenisdokumenModule' },
    { path: 'map-kelompoktransaksi-to-keteranganalasan-cuti', loadChildren : './page/master/master-kelompok-transaksi.module#MapKelompoktransaksiKeteranganalasanModule' },
    { path: 'map-kelompoktransaksi-to-posting-cuti', loadChildren : './page/master/master-kelompok-transaksi.module#MapKelompoktransaksiPostingModule' },
    { path: 'map-kelompoktransaksi-to-strukturnomor-cuti', loadChildren : './page/master/master-kelompok-transaksi.module#MapKelompoktransaksiStrukturnomorModule' },
    { path: 'map-kelompoktransaksi-to-jenisdokumen-cuti', loadChildren : './page/master/master-kelompok-transaksi.module#MapKelompoktransaksiJenisdokumenModule' },
    { path: 'map-kelompoktransaksi-to-keteranganalasan-lembur', loadChildren : './page/master/master-kelompok-transaksi.module#MapKelompoktransaksiKeteranganalasanModule' },
    { path: 'map-kelompoktransaksi-to-posting-lembur', loadChildren : './page/master/master-kelompok-transaksi.module#MapKelompoktransaksiPostingModule' },
    { path: 'map-kelompoktransaksi-to-strukturnomor-lembur', loadChildren : './page/master/master-kelompok-transaksi.module#MapKelompoktransaksiStrukturnomorModule' },
    { path: 'map-kelompoktransaksi-to-jenisdokumen-lembur', loadChildren : './page/master/master-kelompok-transaksi.module#MapKelompoktransaksiJenisdokumenModule' },
    { path: 'map-kelompoktransaksi-to-keteranganalasan-resign', loadChildren : './page/master/master-kelompok-transaksi.module#MapKelompoktransaksiKeteranganalasanModule' },
    { path: 'map-kelompoktransaksi-to-posting-resign', loadChildren : './page/master/master-kelompok-transaksi.module#MapKelompoktransaksiPostingModule' },
    { path: 'map-kelompoktransaksi-to-strukturnomor-resign', loadChildren : './page/master/master-kelompok-transaksi.module#MapKelompoktransaksiStrukturnomorModule' },
    { path: 'map-kelompoktransaksi-to-jenisdokumen-resign', loadChildren : './page/master/master-kelompok-transaksi.module#MapKelompoktransaksiJenisdokumenModule' },
    { path: 'map-kelompoktransaksi-to-keteranganalasan-pinjaman', loadChildren : './page/master/master-kelompok-transaksi.module#MapKelompoktransaksiKeteranganalasanModule' },
    { path: 'map-kelompoktransaksi-to-posting-pinjaman', loadChildren : './page/master/master-kelompok-transaksi.module#MapKelompoktransaksiPostingModule' },
    { path: 'map-kelompoktransaksi-to-strukturnomor-pinjaman', loadChildren : './page/master/master-kelompok-transaksi.module#MapKelompoktransaksiStrukturnomorModule' },
    { path: 'map-kelompoktransaksi-to-jenisdokumen-pinjaman', loadChildren : './page/master/master-kelompok-transaksi.module#MapKelompoktransaksiJenisdokumenModule' },
    { path: 'map-kelompoktransaksi-to-keteranganalasan-reimburs', loadChildren : './page/master/master-kelompok-transaksi.module#MapKelompoktransaksiKeteranganalasanModule' },
    { path: 'map-kelompoktransaksi-to-posting-reimburs', loadChildren : './page/master/master-kelompok-transaksi.module#MapKelompoktransaksiPostingModule' },
    { path: 'map-kelompoktransaksi-to-strukturnomor-reimburs', loadChildren : './page/master/master-kelompok-transaksi.module#MapKelompoktransaksiStrukturnomorModule' },
    { path: 'map-kelompoktransaksi-to-jenisdokumen-reimburs', loadChildren : './page/master/master-kelompok-transaksi.module#MapKelompoktransaksiJenisdokumenModule' },
    { path: 'map-kelompoktransaksi-to-keteranganalasan-reimburs-perjalanan-dinas', loadChildren : './page/master/master-kelompok-transaksi.module#MapKelompoktransaksiKeteranganalasanModule' },
    { path: 'map-kelompoktransaksi-to-posting-reimburs-perjalanan-dinas', loadChildren : './page/master/master-kelompok-transaksi.module#MapKelompoktransaksiPostingModule' },
    { path: 'map-kelompoktransaksi-to-strukturnomor-reimburs-perjalanan-dinas', loadChildren : './page/master/master-kelompok-transaksi.module#MapKelompoktransaksiStrukturnomorModule' },
    { path: 'map-kelompoktransaksi-to-jenisdokumen-reimburs-perjalanan-dinas', loadChildren : './page/master/master-kelompok-transaksi.module#MapKelompoktransaksiJenisdokumenModule' },
    { path: 'map-kelompoktransaksi-to-keteranganalasan-evaluasi', loadChildren : './page/master/master-kelompok-transaksi.module#MapKelompoktransaksiKeteranganalasanModule' },
    { path: 'map-kelompoktransaksi-to-posting-evaluasi', loadChildren : './page/master/master-kelompok-transaksi.module#MapKelompoktransaksiPostingModule' },
    { path: 'map-kelompoktransaksi-to-strukturnomor-evaluasi', loadChildren : './page/master/master-kelompok-transaksi.module#MapKelompoktransaksiStrukturnomorModule' },
    { path: 'map-kelompoktransaksi-to-jenisdokumen-evaluasi', loadChildren : './page/master/master-kelompok-transaksi.module#MapKelompoktransaksiJenisdokumenModule' },
    { path: 'map-kelompoktransaksi-to-keteranganalasan-phk', loadChildren : './page/master/master-kelompok-transaksi.module#MapKelompoktransaksiKeteranganalasanModule' },
    { path: 'map-kelompoktransaksi-to-posting-phk', loadChildren : './page/master/master-kelompok-transaksi.module#MapKelompoktransaksiPostingModule' },
    { path: 'map-kelompoktransaksi-to-strukturnomor-phk', loadChildren : './page/master/master-kelompok-transaksi.module#MapKelompoktransaksiStrukturnomorModule' },
    { path: 'map-kelompoktransaksi-to-jenisdokumen-phk', loadChildren : './page/master/master-kelompok-transaksi.module#MapKelompoktransaksiJenisdokumenModule' },
    { path: 'map-kelompoktransaksi-to-keteranganalasan-pensiun', loadChildren : './page/master/master-kelompok-transaksi.module#MapKelompoktransaksiKeteranganalasanModule' },
    { path: 'map-kelompoktransaksi-to-posting-pensiun', loadChildren : './page/master/master-kelompok-transaksi.module#MapKelompoktransaksiPostingModule' },
    { path: 'map-kelompoktransaksi-to-strukturnomor-pensiun', loadChildren : './page/master/master-kelompok-transaksi.module#MapKelompoktransaksiStrukturnomorModule' },

    { path: 'map-kelompokevaluasi-to-jabatan-evaluasi', loadChildren : './page/master/master-evaluasi-pendidikan.module#MapKelompokevaluasiJabatanModule' },
    { path: 'map-kelompokevaluasi-to-jabatan-orientasi', loadChildren : './page/master/master-evaluasi-pendidikan.module#MapKelompokevaluasiJabatanModule' },

    { path: 'map-kelompok-shift-to-shift-jadwal', loadChildren : './page/master/master-jadwal.module#MapKelompokShiftToShiftModule' },
    { path: 'map-event-to-produk-orientasi', loadChildren : './page/master/master-produk.module#MapEventToProdukModule' },
    { path: 'map-golonganpegawai-to-pangkat-pegawai', loadChildren : './page/master/master-pegawai.module#MapGolonganpegawaiPangkatModule' },
    { path: 'map-angka-to-bulan-sisadmin', loadChildren : './page/master/master-kalender.module#MapAngkaToBulanModule' },
    { path: 'map-objek-modul-to-kelompok-user-sisadmin', loadChildren : './page/master/master-aplikasi.module#MapObjekModulToKelompokUserModule' },
    { path: 'master-map-objek-modul-to-modul-aplikasi-sisadmin', loadChildren : './page/master/master-aplikasi.module#MapObjekModulToModulAplikasiModule' },
 
    { path: 'map-kelompok-user-jabatan', loadChildren : './page/master/master-pegawai.module#MapKelompokUserJabatanModule' },
    { path: 'map-kelompok-user-golonganpegawai', loadChildren : './page/master/master-pegawai.module#MapKelompokUserGolonganPegawaiModule' },
                    
    { path: 'profile-history-strategy-map', loadChildren : './page/master/master-kpi.module#ProfileHistoryStrategyMapModule' },
    { path: 'profile-history-strategy-map-department', loadChildren : './page/master/master-kpi.module#ProfileHistoryStrategyMapDepartmentModule' },
    { path: 'map-kelompok-status-to-status', loadChildren : './page/master/master-kelompok-transaksi.module#MapKelompokStatusToStatusModule' },
    { path: 'map-komponen-to-hasil-pemeriksaan-pegawai', loadChildren : './page/master/master-informasi.module#MapKomponenHasilModule' },
    { path: 'master-map-modul-aplikasi-to-objek-modul-aplikasi-sisadmin', loadChildren : './page/master/master-aplikasi.module#MapModulAplikasiToObjekModulAplikasiModule' },
    { path: 'master-map-bahasa-to-negara-sisadmin', loadChildren : './page/master/master-aplikasi.module#MapBahasaToNegaraModule' },
    { path: 'map-ruangan-to-kasus-penyakit', loadChildren : './page/master/master-kelompok-transaksi.module#MapRuanganToKasusPenyakitModule' },
    //{ path: 'map-kelompok-transaksi-to-ruangan', loadChildren : './page/master/master-kelompok-transaksi.module#MapKelompokTransaksiToRuanganModule' },
    { path: 'map-kelompok-transaksi-to-ruangan', loadChildren : './page/master/master-kelompok-transaksi.module#MapKelompoktransaksiRuanganModule' },
    { path: 'map-ruangan-login-to-ruangan-pelayanan', loadChildren : './page/master/master-kelompok-transaksi.module#MapRuanganLoginToRuanganPelayananModul' },
    { path: 'master-setting-filter-data-registrasi', loadChildren : './page/master/master-kelompok-transaksi.module#MasterSettingFilterDataRegistrasiModul' },

];


