//Menu Surat Keputusan
export const routeMasterSK = [
    { path: 'surat-keputusan', loadChildren : './page/master/master-surat-keputusan.module#SuratKeputusanModule' },
    { path: 'surat-keputusan-sk', loadChildren : './page/master/master-surat-keputusan.module#SuratKeputusanModule' },
    { path: 'surat-keputusan-approval-orientasi', loadChildren : './page/master/master-surat-keputusan.module#SuratKeputusanApprovalModule' },
    { path: 'surat-keputusan-approval-cuti', loadChildren : './page/master/master-surat-keputusan.module#SuratKeputusanApprovalModule' },
    { path: 'surat-keputusan-approval-lembur', loadChildren : './page/master/master-surat-keputusan.module#SuratKeputusanApprovalModule' },
    { path: 'surat-keputusan-approval-resign', loadChildren : './page/master/master-surat-keputusan.module#SuratKeputusanApprovalModule' },
    { path: 'surat-keputusan-approval-reimburs', loadChildren : './page/master/master-surat-keputusan.module#SuratKeputusanApprovalModule' },         
    { path: 'surat-keputusan-approval-award-offence', loadChildren : './page/master/master-surat-keputusan.module#SuratKeputusanApprovalModule' },
    { path: 'surat-keputusan-approval-reimburs-perjalanan-dinas', loadChildren : './page/master/master-surat-keputusan.module#SuratKeputusanApprovalModule' },
    { path: 'surat-keputusan-rate-loan-pinjaman', loadChildren : './page/master/master-surat-keputusan.module#SuratKeputusanRateLoanModule' },
    { path: 'surat-keputusan-approval-pinjaman', loadChildren : './page/master/master-surat-keputusan.module#SuratKeputusanApprovalModule' },
    { path: 'surat-keputusan-approval-perjalanan-dinas', loadChildren : './page/master/master-surat-keputusan.module#SuratKeputusanApprovalModule' },
    { path: 'surat-keputusan-approval-phk', loadChildren : './page/master/master-surat-keputusan.module#SuratKeputusanApprovalModule' },
    { path: 'surat-keputusan-approval-pensiun', loadChildren : './page/master/master-surat-keputusan.module#SuratKeputusanApprovalModule' },
    { path: 'surat-keputusan-approval-evaluasi', loadChildren : './page/master/master-surat-keputusan.module#SuratKeputusanApprovalModule' },
    { path: 'pegawai-sk-gaji', loadChildren : './page/master/master-pegawai-sk.module#PegawaiSkGajiModule' },
    { path: 'pegawai-sk-gaji-ba', loadChildren : './page/master/master-pegawai-sk.module#PegawaiSkGajiBAModule' },
    { path: 'pegawai-sk-gaji-bak', loadChildren : './page/master/master-pegawai-sk.module#PegawaiSkGajiBAKModule' },
    { path: 'pegawai-sk-medical', loadChildren : './page/master/master-pegawai-sk.module#PegawaiSkMedicalModule' },
    { path: 'pegawai-sk-status', loadChildren : './page/master/master-pegawai-sk.module#PegawaiSkStatusModule' },
    { path: 'pegawai-sk-waktu-kerja', loadChildren : './page/master/master-pegawai-sk.module#PegawaiSkWaktuKerjaModule' },
    { path: 'master-struktur-nomor-sk', loadChildren : './page/master/master-khusus.module#StrukturNomorModule' },
    { path: 'master-jenis-keputusan-sk', loadChildren : './page/master/master-khusus.module#JenisKeputusanModule' },
    { path: 'master-jenis-dokumen-sk', loadChildren : './page/master/master-dokumen.module#JenisDokumenModule' },
    { path: 'master-kategori-dokumen-sk', loadChildren : './page/master/master-dokumen.module#KategoriDokumenModule' },
    { path: 'pegawai-sk-fasilitas-fasilitas-pegawai', loadChildren : './page/master/master-pegawai-sk.module#MasterPegawaiSkFasilitasModule' },
    { path: 'pegawai-sk-reimburse-perjalanan-dinas', loadChildren : './page/master/master-pegawai-sk.module#PegawaiSKReimburseModule' },
    { path: 'pegawai-sk-reimburse-reimburs', loadChildren : './page/master/master-pegawai-sk.module#PegawaiSKReimburseModule' },
    { path: 'pegawai-sk-reimburse-reimburs-perjalanan-dinas', loadChildren : './page/master/master-pegawai-sk.module#PegawaiSKReimburseModule' },
    { path: 'pegawai-sk-tidak-absen-jadwal', loadChildren : './page/master/master-pegawai-sk.module#PegawaiSkTidakAbsenModule' },
    { path: 'pegawai-sk-status-revtab-cuti', loadChildren : './page/master/master-pegawai-sk.module#PegawaiSkStatusRevtabModule' },
    { path: 'pegawai-sk-waktu-kerja-lembur', loadChildren : './page/master/master-pegawai-sk.module#PegawaiSkWaktuKerjaModule' },
    { path: 'pegawai-sk-payroll-by-status-lembur', loadChildren : './page/master/master-pegawai-sk.module#PegawaiSkPayrollByStatusModule' },
    { path: 'pegawai-sk-loan-pinjaman', loadChildren : './page/master/master-pegawai-sk.module#PegawaiSKLoanModule' },
    { path: 'pegawai-sk-status-revtab-phk', loadChildren : './page/master/master-pegawai-sk.module#PegawaiSkStatusRevtabModule' },
    { path: 'profile-sk-asuransi', loadChildren : './page/master/master-profile-sk.module#ProfileSKAsuransiModule' },  
    { path: 'master-pegawai-sk-asuransi-asuransi', loadChildren : './page/master/master-pegawai-sk.module#MasterPegawaiSkAsuransiModule' },
    { path: 'pegawai-sk-pajak-pajak', loadChildren : './page/master/master-pegawai-sk.module#PegawaiSkPajakModule' },
    { path: 'pegawai-sk-hitung-payroll-penggajian', loadChildren : './page/master/master-pegawai-sk.module#MasterPegawaiSkHitungPayrollModule' },
    { path: 'profile-sk-komponen-gaji-penggajian', loadChildren : './page/master/master-profile-sk.module#ProfileSkKomponenGajiModule' },
    { path: 'profile-sk-harga-poin', loadChildren : './page/master/master-profile-sk.module#ProfileSkHargaPoinModule' },
    { path: 'pegawai-sk-hitung-payroll-thr', loadChildren : './page/master/master-pegawai-sk.module#MasterPegawaiSkHitungPayrollModule' },
    { path: 'pegawai-sk-hitung-payroll-bonus', loadChildren : './page/master/master-pegawai-sk.module#MasterPegawaiSkHitungPayrollModule' },
    { path: 'pegawai-sk-status-revtab-pensiun', loadChildren : './page/master/master-pegawai-sk.module#PegawaiSkStatusRevtabModule' },
    { path: 'pegawai-sk-status-pensiun-new', loadChildren : './page/master/master-pegawai-sk.module#PegawaiSkStatusPensiunNewModule'},
    { path: 'pegawai-sk-status-cuti-new', loadChildren : './page/master/master-pegawai-sk.module#PegawaiSkStatusCutiNewModule'},
    { path: 'pegawai-sk-hitung-payroll-pesangon', loadChildren : './page/master/master-pegawai-sk.module#MasterPegawaiSkHitungPayrollModule' },
    { path: 'pegawai-sk-status-dinas', loadChildren : './page/master/master-pegawai-sk.module#PegawaiSkStatusDinasModule'},
    { path: 'pegawai-sk-hitung-komponen-ketidakhadiran', loadChildren : './page/master/master-pegawai-sk.module#PegawaiSkHitungKomponenKetidakhadiranModul'},
    { path: 'pegawai-sk-hitung-komponen-keterlambatan', loadChildren : './page/master/master-pegawai-sk.module#PegawaiSkHitungKomponenKeterlambatanModul'},

  
];