    import { Inject, forwardRef, Component, OnInit } from '@angular/core';
    import { HttpClient } from '../../../global/service/HttpClient';
    import { Observable } from 'rxjs/Rx';
    import { GolonganProduk } from './golonganproduk.interface';
    import { Validators, FormControl, FormGroup, FormBuilder } from '@angular/forms';
    import { LazyLoadEvent, ConfirmDialogModule, ConfirmationService, MenuItem } from 'primeng/primeng';
    import { Configuration, AlertService, InfoService, FileService, AuthGuard, ReportService } from '../../../global';
    @Component({
    selector: 'app-golonganproduk',
    templateUrl: 'golonganproduk.component.html',
    styleUrls: ['golonganproduk.component.scss'],
    providers: [ConfirmationService]
    })
    export class GolonganProdukComponent implements OnInit {
    
      item: GolonganProduk = new InisialGolonganProduk();
      selected: GolonganProduk;
      listData: any[];
      dataDummy: {};
      versi: any;
      form: FormGroup;
      formAktif: boolean
      items: MenuItem[];
      pencarian: string;
      report: any;
      toReport: any;
      totalRecords: number;
      page: number;
      rows: number;
      codes: any[];
      kdprof:any;
      kddept:any;
      laporan: boolean = false;
      smbrFile:any; 
      dropdownkelompokProduk:any;
    
      constructor(
        private alertService: AlertService,
        private httpService: HttpClient,
        private confirmationService: ConfirmationService,
        private fb: FormBuilder,
        private fileService: FileService,
        private authGuard: AuthGuard,
        @Inject(forwardRef(() => ReportService)) private print: ReportService) {
      }
      ngOnInit() {
        this.kdprof = this.authGuard.getUserDto().kdProfile;
        this.kddept = this.authGuard.getUserDto().kdDepartemen;
        if (this.page == undefined || this.rows == undefined) {
          this.page = Configuration.get().page;
          this.rows = Configuration.get().rows;
        }
        this.pencarian = ''; 
        this.formAktif = true;
        this.get(this.page, this.rows, this.pencarian);
        this.form = this.fb.group({
       'kode': new FormControl(null),
       'namaGolonganProduk': new FormControl('',Validators.required),
       'reportDisplay': new FormControl('',Validators.required),
       'kdKelompokProduk': new FormControl(null),
       'kodeExternal': new FormControl(null),
       'namaExternal': new FormControl(null),
       'statusEnabled': new FormControl('',Validators.required),
        });
        this.items = [																																																																																	
        {                                                                                                                                                                                                                                                                                                                                                
          label: 'Pdf', icon: 'fa-file-pdf-o', command: () => {                                                                                                                                                                                                                                                                                          
            this.downloadPdf();                                                                                                                                                                                                                                                                                                                          
          }                                                                                                                                                                                                                                                                                                                                              
        },                                                                                                                                                                                                                                                                                                                                               
        {                                                                                                                                                                                                                                                                                                                                                
          label: 'Exel', icon: 'fa-file-excel-o', command: () => {                                                                                                                                                                                                                                                                                       
            this.downloadExel();                                                                                                                                                                                                                                                                                                                         
          }                                                                                                                                                                                                                                                                                                                                              
        }];                                                                                                                                                                                                                                                                                                                                              
        this.getSmbrFile();    
        this.getDrop();                                                                                                                                                                                                                                                                                                                          
     }                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                         
      
      getDrop(){
         this.httpService.get(Configuration.get().dataMaster + '/kelompokproduk/findAllData').subscribe(res => {
          this.dropdownkelompokProduk = []; 
          for (var i = 0; i < res.data.length; i++) {
            this.dropdownkelompokProduk.push({ label: res.data[i].namaKelompokProduk, value: res.data[i].kode.kode })
          };
        });                                                                                                                                                                                                                                                                                                                                                   
      }

      getSmbrFile(){                                                                                                                                                                                                                                                                                                                                     
    		this.httpService.get(Configuration.get().dataMasterNew + '/profile/findProfile').subscribe(table => {                                                                                                                                                                                                                                       
    			this.smbrFile = Configuration.get().resourceFile + '/image/show/' + table.profile.gambarLogo + '?noProfile=true';                                                                                                                                                                                                                       
    		});                                                                                                                                                                                                                                                                                                                                         
    	}                                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                         
      get(page: number, rows: number, search: any) {                                                                                                                                                                                                                                                                                        
        this.httpService.get(Configuration.get().dataMasterNew + '/golonganproduk/findAll?page=' + page + '&rows=' + rows + '&dir=namaGolonganProduk&sort=desc&namaGolonganProduk='+ search).subscribe(table => {                                                                                                      
          this.listData = table.GolonganProduk;                                                                                                                                                                                                                                                                                                   
          this.totalRecords = table.totalRow;                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                         
        });                                                                                                                                                                                                                                                                                                                                              
      }                                                                                                                                                                                                                                                                                                                                                  
      loadPage(event: LazyLoadEvent) {                                                                                                                                                                                                                                                                                                                   
        this.get((event.rows + event.first) / event.rows, event.rows, this.pencarian);                                                                                                                                                                                                                                                
        this.page = (event.rows + event.first) / event.rows;                                                                                                                                                                                                                                                                                             
        this.rows = event.rows;                                                                                                                                                                                                                                                                                                                          
      }                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                         
      cari() {                                                                                                                                                                                                                                                                                                                                           
        this.httpService.get(Configuration.get().dataMasterNew + '/golonganproduk/findAll?page=' + Configuration.get().page + '&rows=' + Configuration.get().rows + '&dir=namaGolonganProduk&sort=desc&namaGolonganProduk=' + this.pencarian).subscribe(table => {                                                     
         this.listData = table.GolonganProduk;                                                                                                                                                                                                                                                                                                    
        });                                                                                                                                                                                                                                                                                                                                              
      }                                                                                                                                                                                                                                                                                                                                                  
      valuechange(newValue) {                                                                                                                                                                                                                                                                                                                            
        this.report = newValue;                                                                                                                                                                                                                                                                                                                          
      }                                                                                                                                                                                                                                                                                                                                                  
      downloadExel() {                                                                                                                                                                                                                                                                                                                                   
        this.httpService.get(Configuration.get().dataMasterNew + '/golonganproduk/findAll?page='+this.page+'&rows='+this.rows+'&dir=namaGolonganProduk&sort=desc').subscribe(table => {                                                                                                                                       
          this.listData = table.GolonganProduk;                                                                                                                                                                                                                                                                                                   
          this.codes = [];                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                         
          for (let i = 0; i < this.listData.length; i++) {                                                                                                                                                                                                                                                                                               
              this.codes.push({                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                         
                kode: this.listData[i].kode.kode,                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                         
              })                                                                                                                                                                                                                                                                                                                                         
         }                                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                         
          this.fileService.exportAsExcelFile(this.codes, 'golonganProduk');                                                                                                                                                                                                                                                          
        });                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                         
      }                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                         
      downloadPdf() {                                                                                                                                                                                                                                                                                                                                    
        let cetak = Configuration.get().report + '/golonganProduk/laporanGolonganProduk.pdf?kdDepartemen='+this.kddept+'&kdProfile='+this.kdprof+'&gambarLogo=' + this.smbrFile +'&download=true';                                                                                                                            
        window.open(cetak);                                                                                                                                                                                                                                                                                                                              
      }                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                         
      confirmDelete() {                                                                                                                                                                                                                                                                                                                                  
        let kode = this.form.get('kode').value;                                                                                                                                                                                                                                                                                                          
        if (kode == null || kode == undefined || kode == "") {                                                                                                                                                                                                                                                                                           
          this.alertService.warn('Peringatan', 'Pilih Daftar Master GolonganProduk');                                                                                                                                                                                                                                                             
        } else {                                                                                                                                                                                                                                                                                                                                         
          this.confirmationService.confirm({                                                                                                                                                                                                                                                                                                             
            message: 'Apakah data akan di hapus?',                                                                                                                                                                                                                                                                                                       
            header: 'Konfirmasi Hapus',                                                                                                                                                                                                                                                                                                                  
            icon: 'fa fa-trash',                                                                                                                                                                                                                                                                                                                         
           accept: () => {                                                                                                                                                                                                                                                                                                                               
             this.hapus();                                                                                                                                                                                                                                                                                                                               
            },                                                                                                                                                                                                                                                                                                                                           
            reject: () => {                                                                                                                                                                                                                                                                                                                              
              this.alertService.warn('Peringatan', 'Data Tidak Dihapus');                                                                                                                                                                                                                                                                                
            }                                                                                                                                                                                                                                                                                                                                            
          });                                                                                                                                                                                                                                                                                                                                            
        }                                                                                                                                                                                                                                                                                                                                                
      }                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                         
      hapus() {                                                                                                                                                                                                                                                                                                                                          
       let item = [...this.listData];                                                                                                                                                                                                                                                                                                                    
        let deleteItem = item[this.findSelectedIndex()];                                                                                                                                                                                                                                                                                                 
        this.httpService.delete(Configuration.get().dataMasterNew + '/golonganproduk/del/' + deleteItem.kode.kode).subscribe(response => {                                                                                                                                                                                           
          this.alertService.success('Berhasil', 'Data Dihapus');                                                                                                                                                                                                                                                                                         
          this.reset();                                                                                                                                                                                                                                                                                                                                  
        });                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                         
     }                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                         
      findSelectedIndex(): number {                                                                                                                                                                                                                                                                                                                      
        return this.listData.indexOf(this.selected);                                                                                                                                                                                                                                                                                                     
      }                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                         
     reset() {                                                                                                                                                                                                                                                                                                                                          
       this.ngOnInit();                                                                                                                                                                                                                                                                                                                                 
      }                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                         
      confirmUpdate() {                                                                                                                                                                                                                                                                                                                                  
       this.confirmationService.confirm({                                                                                                                                                                                                                                                                                                                
          message: 'Apakah data akan diperbaharui?',                                                                                                                                                                                                                                                                                                     
         header: 'Konfirmasi Pembaharuan',                                                                                                                                                                                                                                                                                                              
          accept: () => {                                                                                                                                                                                                                                                                                                                               
            this.update();                                                                                                                                                                                                                                                                                                                              
          },                                                                                                                                                                                                                                                                                                                                            
          reject: () => {                                                                                                                                                                                                                                                                                                                               
            this.alertService.warn('Peringatan', 'Data Tidak Diperbaharui');                                                                                                                                                                                                                                                                            
          }                                                                                                                                                                                                                                                                                                                                             
        });                                                                                                                                                                                                                                                                                                                                             
      }                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                        
      update() {                                                                                                                                                                                                                                                                                                                                        
        this.httpService.update(Configuration.get().dataMasterNew + '/golonganproduk/update', this.form.value).subscribe(response => {                                                                                                                                                                                              
          this.alertService.success('Berhasil', 'Data Diperbarui');                                                                                                                                                                                                                                                                                     
          // this.get(this.page, this.rows, this.pencarian);                                                                                                                                                                                                                                                                                            
          this.reset();                                                                                                                                                                                                                                                                                                                                 
        });                                                                                                                                                                                                                                                                                                                                             
      }                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                        
      simpan() {                                                                                                                                                                                                                                                                                                                                        
        if (this.formAktif == false) {                                                                                                                                                                                                                                                                                                                  
          this.confirmUpdate()                                                                                                                                                                                                                                                                                                                          
        } else {                                                                                                                                                                                                                                                                                                                                        
          this.httpService.post(Configuration.get().dataMasterNew + '/golonganproduk/save', this.form.value).subscribe(response => {                                                                                                                                                                                                
            this.alertService.success('Berhasil', 'Data Disimpan');                                                                                                                                                                                                                                                                                     
            // this.get(this.page, this.rows, this.pencarian);                                                                                                                                                                                                                                                                                          
            this.reset();                                                                                                                                                                                                                                                                                                                               
          });                                                                                                                                                                                                                                                                                                                                           
        }                                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                        
      }                                                                                                                                                                                                                                                                                                                                                 
      validateAllFormFields(formGroup: FormGroup) {                                                                                                                                                                                                                                                                                                     
        Object.keys(formGroup.controls).forEach(field => {                                                                                                                                                                                                                                                                                              
          const control = formGroup.get(field);                                                                                                                                                                                                                                                                                                         
          if (control instanceof FormControl) {                                                                                                                                                                                                                                                                                                         
            control.markAsTouched({ onlySelf: true });                                                                                                                                                                                                                                                                                                  
          } else if (control instanceof FormGroup) {                                                                                                                                                                                                                                                                                                    
            this.validateAllFormFields(control);                                                                                                                                                                                                                                                                                                        
          }                                                                                                                                                                                                                                                                                                                                             
        });                                                                                                                                                                                                                                                                                                                                             
      }                                                                                                                                                                                                                                                                                                                                                 
      onSubmit() {                                                                                                                                                                                                                                                                                                                                      
        if (this.form.invalid) {                                                                                                                                                                                                                                                                                                                        
          this.validateAllFormFields(this.form);                                                                                                                                                                                                                                                                                                        
          this.alertService.warn("Peringatan", "Data Tidak Sesuai")                                                                                                                                                                                                                                                                                     
        } else {                                                                                                                                                                                                                                                                                                                                        
          this.simpan();                                                                                                                                                                                                                                                                                                                                
        }                                                                                                                                                                                                                                                                                                                                               
      }                                                                                                                                                                                                                                                                                                                                                 
      onRowSelect(event) {                                                                                                                                                                                                                                                                                                                              
        this.formAktif = false;                                                                                                                                                                                                                                                                                                                         
        let cloned = this.clone(event.data);                                                                                                                                                                                                                                                                                                            
        this.form.setValue(cloned);                                                                                                                                                                                                                                                                                                                     
      }                                                                                                                                                                                                                                                                                                                                                 
      clone(cloned: GolonganProduk): GolonganProduk {                                                                                                                                                                                                                                                                                                                       
        let hub = new InisialGolonganProduk();                                                                                                                                                                                                                                                                                                   
        for (let prop in cloned) {                                                                                                                                                                                                                                                                                                                      
          hub[prop] = cloned[prop];                                                                                                                                                                                                                                                                                                                     
        }                                                                                                                                                                                                                                                                                                                                               
        let fixHub = new InisialGolonganProduk();                                                                                                                                                                                                                                                                                                
        fixHub = {                                                                                                                                                                                                                                                                                                                                      
         "kode": hub.kode.kode,   
         "namaGolonganProduk": hub.namaGolonganProduk,   
         "reportDisplay": hub.reportDisplay,   
         "kdKelompokProduk": hub.kdKelompokProduk,   
         "kodeExternal": hub.kodeExternal,   
         "namaExternal": hub.namaExternal,   
         "statusEnabled": hub.statusEnabled,   
        }                                                                                                                                                                                                                                                                                                                                               
        return fixHub;                                                                                                                                                                                                                                                                                                                                  
      }                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                        
      cetak() {                                                                                                                                                                                                                                                                                                                                         
        this.laporan = true;                                                                                                                                                                                                                                                                                                                            
        this.print.showEmbedPDFReport(Configuration.get().report + '/golonganProduk/laporanGolonganProduk.pdf?kdDepartemen='+this.kddept+'&kdProfile='+this.kdprof+'&gambarLogo=' + this.smbrFile +'&download=false', 'frmGolonganProduk(_laporanCetak');                                                                               
    }                                                                                                                                                                                                                                                                                                                                                   
    tutupLaporan() {                                                                                                                                                                                                                                                                                                                                    
      this.laporan = false;                                                                                                                                                                                                                                                                                                                             
    }                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                        
    }                                                                                                                                                                                                                                                                                                                                                   
    class InisialGolonganProduk implements GolonganProduk {                                                                                                                                                                                                                                                                               
      constructor(                                                                                                                                                                                                                                                                                                                                      
        public kode?,                                                                                                                                                                                                                                                                                                                                   
         public namaGolonganProduk?,   
         public reportDisplay?,   
         public kdKelompokProduk?,   
         public kodeExternal?,   
         public namaExternal?,   
         public statusEnabled?,   
        )                                                                                                                                                                                                                                                                                                                                               
      { }                                                                                                                                                                                                                                                                                                                                               
    }                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                            

