    import { Inject, forwardRef, Component, OnInit } from '@angular/core';
    import { HttpClient } from '../../../global/service/HttpClient';
    import { Observable } from 'rxjs/Rx';
    import { FreqAskQuestions } from './freqaskquestions.interface';
    import { Validators, FormControl, FormGroup, FormBuilder } from '@angular/forms';
    import { LazyLoadEvent, ConfirmDialogModule, ConfirmationService, MenuItem } from 'primeng/primeng';
    import { Configuration, AlertService, InfoService, FileService, AuthGuard, ReportService } from '../../../global';
    @Component({
    selector: 'app-freqaskquestions',
    templateUrl: 'freqaskquestions.component.html',
    styleUrls: ['freqaskquestions.component.scss'],
    providers: [ConfirmationService]
    })
    export class FreqAskQuestionsComponent implements OnInit {
    
      item: FreqAskQuestions = new InisialFreqAskQuestions();
      selected: FreqAskQuestions;
      listData: any[];
      dataDummy: {};
      versi: any;
      form: FormGroup;
      formAktif: boolean
      items: MenuItem[];
      pencarian: string;
      report: any;
      toReport: any;
      totalRecords: number;
      page: number;
      rows: number;
      codes: any[];
      kdprof:any;
      kddept:any;
      laporan: boolean = false;
      smbrFile:any; 
      dropdownproduk:any;
      dropdowndeskripsi:any;
      autokdProduk:any;
      autokdDeskripsi:any;
      namaProduk:any;
      namaDeskripsi:any;
      constructor(
        private alertService: AlertService,
        private httpService: HttpClient,
        private confirmationService: ConfirmationService,
        private fb: FormBuilder,
        private fileService: FileService,
        private authGuard: AuthGuard,
        @Inject(forwardRef(() => ReportService)) private print: ReportService) {
      }
      ngOnInit() {
        this.kdprof = this.authGuard.getUserDto().kdProfile;
        this.kddept = this.authGuard.getUserDto().kdDepartemen;
        if (this.page == undefined || this.rows == undefined) {
          this.page = Configuration.get().page;
          this.rows = Configuration.get().rows;
        }
        this.pencarian = ''; 
        this.formAktif = true;
        this.get(this.page, this.rows, this.pencarian);
        this.form = this.fb.group({ 
         'autokdProduk': new FormControl('',Validators.required),
         'autokdDeskripsi': new FormControl('',Validators.required),
         'kdProduk': new FormControl('',Validators.required),
         'kdDeskripsi': new FormControl('',Validators.required),
         'detailDeskripsi': new FormControl(null),
         'keteranganLainnya': new FormControl(null),
         'statusEnabled': new FormControl('',Validators.required),
        });
        this.items = [																																																																																	
        {                                                                                                                                                                                                                                                                                                                                                
          label: 'Pdf', icon: 'fa-file-pdf-o', command: () => {                                                                                                                                                                                                                                                                                          
            this.downloadPdf();                                                                                                                                                                                                                                                                                                                          
          }                                                                                                                                                                                                                                                                                                                                              
        },                                                                                                                                                                                                                                                                                                                                               
        {                                                                                                                                                                                                                                                                                                                                                
          label: 'Exel', icon: 'fa-file-excel-o', command: () => {                                                                                                                                                                                                                                                                                       
            this.downloadExel();                                                                                                                                                                                                                                                                                                                         
          }                                                                                                                                                                                                                                                                                                                                              
        }];                                                                                                                                                                                                                                                                                                                                              
        this.getSmbrFile();        
        this.getDrop();                                                                                                                                                                                                                                                                                                                    
     }                                                                                                                                                                                                                                                                                                                                                   
                     
      getDropProduk(newValue){ 
          this.httpService.get(Configuration.get().dataMasterNew + '/produk/findAllDrop?page=1&rows10&dir=namaProduk&sort=asc&namaProduk=' + newValue.query)
        .subscribe(table => {
          this.dropdownproduk = table.Produk;  
        });         
      }     

       getDrop(){        
          this.httpService.get(Configuration.get().dataMasterNew + '/deskripsi/findAllData')
          .subscribe(table => {
          this.dropdowndeskripsi = table.Deskripsi;
          
        });          
          this.httpService.get(Configuration.get().dataMasterNew + '/produk/findAllData')
          .subscribe(table => {
          this.dropdownproduk = table.Produk;  
        });         
      }     

       getDropDeskripsi(newValue){        
          this.httpService.get(Configuration.get().dataMasterNew + '/deskripsi/findAll?page=1&rows10&dir=namaDeskripsi&sort=asc&namaDeskripsi=' + newValue.query)
          .subscribe(table => {
          this.dropdowndeskripsi = table.Deskripsi;
          
        });         
      }                                                                                                                                                                                                                                                                                                                                  
             
      pilihDeskripsi(event) {
        this.form.get('detailDeskripsi').setValue(event.detailDeskripsi);
        this.form.get('kdDeskripsi').setValue(event.kode.kode); 
     }              
       
     pilihProduk(event) {
        this.form.get('kdProduk').setValue(event.kode);        
     }                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                         
      getSmbrFile(){                                                                                                                                                                                                                                                                                                                                     
    		this.httpService.get(Configuration.get().dataMasterNew + '/profile/findProfile').subscribe(table => {                                                                                                                                                                                                                                       
    			this.smbrFile = Configuration.get().resourceFile + '/image/show/' + table.profile.gambarLogo + '?noProfile=true';                                                                                                                                                                                                                       
    		});                                                                                                                                                                                                                                                                                                                                         
    	}                                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                         
      get(page: number, rows: number, search: any) {                                                                                                                                                                                                                                                                                        
        this.httpService.get(Configuration.get().dataMasterNew + '/freqaskquestions/findAll?page=' + page + '&rows=' + rows + '&dir=id.kdProduk&sort=desc&namaFreqAskQuestions='+ search).subscribe(table => {                                                                                                      
          this.listData = table.FreqAskQuestions;                                                                                                                                                                                                                                                                                                   
          this.totalRecords = table.totalRow;                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                         
        });                                                                                                                                                                                                                                                                                                                                              
      }                                                                                                                                                                                                                                                                                                                                                  
      loadPage(event: LazyLoadEvent) {                                                                                                                                                                                                                                                                                                                   
        this.get((event.rows + event.first) / event.rows, event.rows, this.pencarian);                                                                                                                                                                                                                                                
        this.page = (event.rows + event.first) / event.rows;                                                                                                                                                                                                                                                                                             
        this.rows = event.rows;                                                                                                                                                                                                                                                                                                                          
      }                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                         
      cari() {                                                                                                                                                                                                                                                                                                                                           
        this.httpService.get(Configuration.get().dataMasterNew + '/freqaskquestions/findAll?page=' + Configuration.get().page + '&rows=' + Configuration.get().rows + '&dir=id.kdProduk&sort=desc&namaFreqAskQuestions=' + this.pencarian).subscribe(table => {                                                     
         this.listData = table.FreqAskQuestions;                                                                                                                                                                                                                                                                                                    
        });                                                                                                                                                                                                                                                                                                                                              
      }                                                                                                                                                                                                                                                                                                                                                  
      valuechange(newValue) {                                                                                                                                                                                                                                                                                                                            
        this.report = newValue;                                                                                                                                                                                                                                                                                                                          
      }                                                                                                                                                                                                                                                                                                                                                  
      downloadExel() {                                                                                                                                                                                                                                                                                                                                   
        this.httpService.get(Configuration.get().dataMasterNew + '/freqaskquestions/findAll?page='+this.page+'&rows='+this.rows+'&dir=id.kdProduk&sort=desc').subscribe(table => {                                                                                                                                       
          this.listData = table.FreqAskQuestions;                                                                                                                                                                                                                                                                                                   
          this.codes = [];                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                         
          for (let i = 0; i < this.listData.length; i++) {                                                                                                                                                                                                                                                                                               
              this.codes.push({                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                         
                kode: this.listData[i].kode.kode,                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                         
              })                                                                                                                                                                                                                                                                                                                                         
         }                                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                         
          this.fileService.exportAsExcelFile(this.codes, 'freqAskQuestions');                                                                                                                                                                                                                                                          
        });                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                         
      }                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                         
      downloadPdf() {                                                                                                                                                                                                                                                                                                                                    
        let cetak = Configuration.get().report + '/freqAskQuestions/laporanFreqAskQuestions.pdf?kdDepartemen='+this.kddept+'&kdProfile='+this.kdprof+'&gambarLogo=' + this.smbrFile +'&download=true';                                                                                                                            
        window.open(cetak);                                                                                                                                                                                                                                                                                                                              
      }                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                         
      confirmDelete() {                                                                                                                                                                                                                                                                                                                                  
        let kodeP = this.form.get('kdProduk').value;     
        let kodeD = this.form.get('kdDeskripsi').value;                                                                                                                                                                                                                                                                                                          
        if (kodeP == null || kodeP == undefined || kodeP == "" || kodeD == null || kodeD == undefined || kodeD == "") {                                                                                                                                                                                                                                                                                           
          this.alertService.warn('Peringatan', 'Pilih Daftar Master FreqAskQuestions');                                                                                                                                                                                                                                                             
        } else {                                                                                                                                                                                                                                                                                                                                         
          this.confirmationService.confirm({                                                                                                                                                                                                                                                                                                             
            message: 'Apakah data akan di hapus?',                                                                                                                                                                                                                                                                                                       
            header: 'Konfirmasi Hapus',                                                                                                                                                                                                                                                                                                                  
            icon: 'fa fa-trash',                                                                                                                                                                                                                                                                                                                         
           accept: () => {                                                                                                                                                                                                                                                                                                                               
             this.hapus();                                                                                                                                                                                                                                                                                                                               
            },                                                                                                                                                                                                                                                                                                                                           
            reject: () => {                                                                                                                                                                                                                                                                                                                              
              this.alertService.warn('Peringatan', 'Data Tidak Dihapus');                                                                                                                                                                                                                                                                                
            }                                                                                                                                                                                                                                                                                                                                            
          });                                                                                                                                                                                                                                                                                                                                            
        }                                                                                                                                                                                                                                                                                                                                                
      }                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                         
      hapus() {                                                                                                                                                                                                                                                                                                                                          
       let item = [...this.listData];                                                                                                                                                                                                                                                                                                                    
        let deleteItem = item[this.findSelectedIndex()];                                                                                                                                                                                                                                                                                                 
        this.httpService.delete(Configuration.get().dataMasterNew + '/freqaskquestions/del/' + deleteItem.kode.kdProduk +'/' + deleteItem.kode.kdDeskripsi).subscribe(response => {                                                                                                                                                                                           
          this.alertService.success('Berhasil', 'Data Dihapus');                                                                                                                                                                                                                                                                                         
          this.reset();                                                                                                                                                                                                                                                                                                                                  
        });                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                         
     }                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                         
      findSelectedIndex(): number {                                                                                                                                                                                                                                                                                                                      
        return this.listData.indexOf(this.selected);                                                                                                                                                                                                                                                                                                     
      }                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                         
     reset() {                                                                                                                                                                                                                                                                                                                                          
       this.ngOnInit();                                                                                                                                                                                                                                                                                                                                 
      }                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                         
      confirmUpdate() {                                                                                                                                                                                                                                                                                                                                  
       this.confirmationService.confirm({                                                                                                                                                                                                                                                                                                                
          message: 'Apakah data akan diperbaharui?',                                                                                                                                                                                                                                                                                                     
         header: 'Konfirmasi Pembaharuan',                                                                                                                                                                                                                                                                                                              
          accept: () => {                                                                                                                                                                                                                                                                                                                               
            this.update();                                                                                                                                                                                                                                                                                                                              
          },                                                                                                                                                                                                                                                                                                                                            
          reject: () => {                                                                                                                                                                                                                                                                                                                               
            this.alertService.warn('Peringatan', 'Data Tidak Diperbaharui');                                                                                                                                                                                                                                                                            
          }                                                                                                                                                                                                                                                                                                                                             
        });                                                                                                                                                                                                                                                                                                                                             
      }                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                        
      update() {                                                                                                                                                                                                                                                                                                                                        
        this.httpService.update(Configuration.get().dataMasterNew + '/freqaskquestions/update', this.form.value).subscribe(response => {                                                                                                                                                                                              
          this.alertService.success('Berhasil', 'Data Diperbarui');                                                                                                                                                                                                                                                                                     
          // this.get(this.page, this.rows, this.pencarian);                                                                                                                                                                                                                                                                                            
          this.reset();                                                                                                                                                                                                                                                                                                                                 
        });                                                                                                                                                                                                                                                                                                                                             
      }                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                        
      simpan() {                                                                                                                                                                                                                                                                                                                                        
        if (this.formAktif == false) {                                                                                                                                                                                                                                                                                                                  
          this.confirmUpdate()                                                                                                                                                                                                                                                                                                                          
        } else {               
          let fixHub = new InisialFreqAskQuestions();                                                                                                                                                                                                                                                                                                
        fixHub = {                 
         "kdProduk": this.form.get('kdProduk').value,   
         "kdDeskripsi": this.form.get('kdDeskripsi').value,   
         "keteranganLainnya":  this.form.get('keteranganLainnya').value,   
         "statusEnabled":  this.form.get('statusEnabled').value,   
        }                                                                                                                                                                                                                                                                                                                                      
          this.httpService.post(Configuration.get().dataMasterNew + '/freqaskquestions/save', this.form.value).subscribe(response => {                                                                                                                                                                                                
            this.alertService.success('Berhasil', 'Data Disimpan');                                                                                                                                                                                                                                                                                     
            // this.get(this.page, this.rows, this.pencarian);                                                                                                                                                                                                                                                                                          
            this.reset();                                                                                                                                                                                                                                                                                                                               
          });                                                                                                                                                                                                                                                                                                                                           
        }                                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                        
      }                                                                                                                                                                                                                                                                                                                                                 
      validateAllFormFields(formGroup: FormGroup) {                                                                                                                                                                                                                                                                                                     
        Object.keys(formGroup.controls).forEach(field => {                                                                                                                                                                                                                                                                                              
          const control = formGroup.get(field);                                                                                                                                                                                                                                                                                                         
          if (control instanceof FormControl) {                                                                                                                                                                                                                                                                                                         
            control.markAsTouched({ onlySelf: true });                                                                                                                                                                                                                                                                                                  
          } else if (control instanceof FormGroup) {                                                                                                                                                                                                                                                                                                    
            this.validateAllFormFields(control);                                                                                                                                                                                                                                                                                                        
          }                                                                                                                                                                                                                                                                                                                                             
        });                                                                                                                                                                                                                                                                                                                                             
      }                                                                                                                                                                                                                                                                                                                                                 
      onSubmit() {                                                                                                                                                                                                                                                                                                                                      
        if (this.form.invalid) {                                                                                                                                                                                                                                                                                                                        
          this.validateAllFormFields(this.form);                                                                                                                                                                                                                                                                                                        
          this.alertService.warn("Peringatan", "Data Tidak Sesuai")                                                                                                                                                                                                                                                                                     
        } else {                                                                                                                                                                                                                                                                                                                                        
          this.simpan();                                                                                                                                                                                                                                                                                                                                
        }                                                                                                                                                                                                                                                                                                                                               
      }                                                                                                                                                                                                                                                                                                                                                 
      onRowSelect(event) {                                                                                                                                                                                                                                                                                                                              
        this.formAktif = false;                                                                                                                                                                                                                                                                                                                         
        let cloned = this.clone(event.data);                                                                                                                                                                                                                                                                                                            
        this.form.setValue(cloned);                                                                                                                                                                                                                                                                                                                     
      }                                                                                                                                                                                                                                                                                                                                                 
      clone(cloned: FreqAskQuestions): FreqAskQuestions {                                                                                                                                                                                                                                                                                                                       
        let hub = new InisialFreqAskQuestions();                                                                                                                                                                                                                                                                                                   
        for (let prop in cloned) {                                                                                                                                                                                                                                                                                                                      
          hub[prop] = cloned[prop];                                                                                                                                                                                                                                                                                                                     
        }                                                                                                                                                                                                                                                                                                                                               
        let fixHub = new InisialFreqAskQuestions();  

        fixHub = {                 
         "kdProduk": hub.kode.kdProduk,   
         "kdDeskripsi": hub.kode.kdDeskripsi,   
         "autokdProduk": {'kode': hub.kode.kdProduk, 'namaProduk': hub.namaProduk},   
         "autokdDeskripsi": {'kode': hub.kode.kdDeskripsi, 'namaDeskripsi': hub.namaDeskripsi},  
         "detailDeskripsi": hub.detailDeskripsi,  
         "keteranganLainnya": hub.keteranganLainnya,   
         "statusEnabled": hub.statusEnabled,   
        }                                                                                                                                                                                                                                                                                                                                               
        return fixHub;                                                                                                                                                                                                                                                                                                                                  
      }                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                        
      cetak() {                                                                                                                                                                                                                                                                                                                                         
        this.laporan = true;                                                                                                                                                                                                                                                                                                                            
        this.print.showEmbedPDFReport(Configuration.get().report + '/freqAskQuestions/laporanFreqAskQuestions.pdf?kdDepartemen='+this.kddept+'&kdProfile='+this.kdprof+'&gambarLogo=' + this.smbrFile +'&download=false', 'frmFreqAskQuestions(_laporanCetak');                                                                               
    }                                                                                                                                                                                                                                                                                                                                                   
    tutupLaporan() {                                                                                                                                                                                                                                                                                                                                    
      this.laporan = false;                                                                                                                                                                                                                                                                                                                             
    }                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                        
    }                                                                                                                                                                                                                                                                                                                                                   
    class InisialFreqAskQuestions implements FreqAskQuestions {                                                                                                                                                                                                                                                                               
      constructor(          
         public kode?,                                                                                                                                                                                                                                                                                                                             
         public kdProduk?,   
         public kdDeskripsi?,   
         public keteranganLainnya?,   
         public statusEnabled?,   
         public autokdProduk?, 
         public autokdDeskripsi?,  
         public detailDeskripsi?,  
         public  namaProduk?, 
         public namaDeskripsi?, 
        )                                                                                                                                                                                                                                                                                                                                               
      { }                                                                                                                                                                                                                                                                                                                                               
    }                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                            

