    import { Inject, forwardRef, Component, OnInit } from '@angular/core';
    import { HttpClient } from '../../../global/service/HttpClient';
    import { Observable } from 'rxjs/Rx';
    import { ChartOfAccount } from './chartofaccount.interface';
    import { Validators, FormControl, FormGroup, FormBuilder } from '@angular/forms';
    import { LazyLoadEvent, ConfirmDialogModule, ConfirmationService, MenuItem } from 'primeng/primeng';
    import { Configuration, AlertService, InfoService, FileService, AuthGuard, ReportService } from '../../../global';
    @Component({
    selector: 'app-chartofaccount',
    templateUrl: 'chartofaccount.component.html',
    styleUrls: ['chartofaccount.component.scss'],
    providers: [ConfirmationService]
    })
    export class ChartOfAccountComponent implements OnInit {
    
      item: ChartOfAccount = new InisialChartOfAccount();
      selected: ChartOfAccount;
      listData: any[];
      dataDummy: {};
      versi: any;
      form: FormGroup;
      formAktif: boolean
      items: MenuItem[];
      pencarian: string;
      report: any;
      toReport: any;
      totalRecords: number;
      page: number;
      rows: number;
      codes: any[];
      kdprof:any;
      kddept:any;
      laporan: boolean = false;
      smbrFile:any;       
      dropdownjenisAccount:any; 
      dropdownkategoryAccount:any; 
      dropdownstatusAccount:any; 
      dropdownstrukturNomor:any; 
      dropdownaccountHead:any; 
    
      constructor(
        private alertService: AlertService,
        private httpService: HttpClient,
        private confirmationService: ConfirmationService,
        private fb: FormBuilder,
        private fileService: FileService,
        private authGuard: AuthGuard,
        @Inject(forwardRef(() => ReportService)) private print: ReportService) {
      }
      ngOnInit() {
        this.kdprof = this.authGuard.getUserDto().kdProfile;
        this.kddept = this.authGuard.getUserDto().kdDepartemen;
        if (this.page == undefined || this.rows == undefined) {
          this.page = Configuration.get().page;
          this.rows = Configuration.get().rows;
        }
        this.pencarian = ''; 
        this.formAktif = true;
        this.get(this.page, this.rows, this.pencarian);
        this.form = this.fb.group({
       'kode': new FormControl(null), 
       'noAccount': new FormControl('',Validators.required),
       'namaAccount': new FormControl('',Validators.required),
       'reportDisplay': new FormControl('',Validators.required),
       'saldoNormal': new FormControl('',Validators.required),
       'kdJenisAccount': new FormControl('',Validators.required),
       'kdKategoryAccount': new FormControl('',Validators.required),
       'kdStatusAccount': new FormControl('',Validators.required),
       'kdStrukturNomor': new FormControl('',Validators.required),
       'kdAccountHead': new FormControl(null),
       'saldoAwalKTahunBerjalan': new FormControl('',Validators.required),
       'saldoAwalDTahunBerjalan': new FormControl('',Validators.required),
       'saldoAkhirKTahunBerjalan': new FormControl('',Validators.required),
       'saldoAkhirDTahunBerjalan': new FormControl('',Validators.required),
       'kodeExternal': new FormControl(null),
       'namaExternal': new FormControl(null),
       'statusEnabled': new FormControl('',Validators.required),
        });
        this.items = [																																																																																	
        {                                                                                                                                                                                                                                                                                                                                                
          label: 'Pdf', icon: 'fa-file-pdf-o', command: () => {                                                                                                                                                                                                                                                                                          
            this.downloadPdf();                                                                                                                                                                                                                                                                                                                          
          }                                                                                                                                                                                                                                                                                                                                              
        },                                                                                                                                                                                                                                                                                                                                               
        {                                                                                                                                                                                                                                                                                                                                                
          label: 'Exel', icon: 'fa-file-excel-o', command: () => {                                                                                                                                                                                                                                                                                       
            this.downloadExel();                                                                                                                                                                                                                                                                                                                         
          }                                                                                                                                                                                                                                                                                                                                              
        }];                                                                                                                                                                                                                                                                                                                                              
        this.getSmbrFile();     
        this.getDrop();                                                                                                                                                                                                                                                                                                                         
     }     

      getDrop(){
         this.httpService.get(Configuration.get().dataMaster + '/jenisaccount/findAllData').subscribe(res => {
          this.dropdownjenisAccount = []; 
          for (var i = 0; i < res.data.length; i++) {
            this.dropdownjenisAccount.push({ label: res.data[i].namaJenisAccount, value: res.data[i].kode.kode })
          };
        });  

         this.httpService.get(Configuration.get().dataMaster + '/kategoryaccount/findAllData').subscribe(res => {
          this.dropdownkategoryAccount = []; 
          for (var i = 0; i < res.data.length; i++) {
            this.dropdownkategoryAccount.push({ label: res.data[i].namaKategoryAccount, value: res.data[i].kode.kode })
          };
        }); 

         this.httpService.get(Configuration.get().dataMaster + '/status/status-account').subscribe(res => {
          this.dropdownstatusAccount = []; 
          for (var i = 0; i < res.data.length; i++) {
            this.dropdownstatusAccount.push({ label: res.data[i].namaStatus, value: res.data[i].kode.kode })
          };
        }); 

         this.httpService.get(Configuration.get().dataMaster + '/strukturnomor/findAllData').subscribe(res => {
          this.dropdownstrukturNomor = []; 
          for (var i = 0; i < res.data.length; i++) {
            this.dropdownstrukturNomor.push({ label: res.data[i].namaStrukturNomor, value: res.data[i].kode.kode })
          };
        }); 

         this.httpService.get(Configuration.get().dataMaster + '/chartofaccount/findAllHead').subscribe(res => {
          this.dropdownaccountHead = []; 
          for (var i = 0; i < res.data.length; i++) {
            this.dropdownaccountHead.push({ label: res.data[i].namaAccount, value: res.data[i].kode.kdAccount })
          };
        }); 
      }                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                         
      getSmbrFile(){                                                                                                                                                                                                                                                                                                                                     
    		this.httpService.get(Configuration.get().dataMasterNew + '/profile/findProfile').subscribe(table => {                                                                                                                                                                                                                                       
    			this.smbrFile = Configuration.get().resourceFile + '/image/show/' + table.profile.gambarLogo + '?noProfile=true';                                                                                                                                                                                                                       
    		});                                                                                                                                                                                                                                                                                                                                         
    	}                                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                         
      get(page: number, rows: number, search: any) {                                                                                                                                                                                                                                                                                        
        this.httpService.get(Configuration.get().dataMasterNew + '/chartofaccount/findAll?page=' + page + '&rows=' + rows + '&dir=namaAccount&sort=desc&namaAccount='+ search).subscribe(table => {                                                                                                      
          this.listData = table.ChartOfAccount;                                                                                                                                                                                                                                                                                                   
          this.totalRecords = table.totalRow;                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                         
        });                                                                                                                                                                                                                                                                                                                                              
      }                                                                                                                                                                                                                                                                                                                                                  
      loadPage(event: LazyLoadEvent) {                                                                                                                                                                                                                                                                                                                   
        this.get((event.rows + event.first) / event.rows, event.rows, this.pencarian);                                                                                                                                                                                                                                                
        this.page = (event.rows + event.first) / event.rows;                                                                                                                                                                                                                                                                                             
        this.rows = event.rows;                                                                                                                                                                                                                                                                                                                          
      }                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                         
      cari() {                                                                                                                                                                                                                                                                                                                                           
        this.httpService.get(Configuration.get().dataMasterNew + '/chartofaccount/findAll?page=' + Configuration.get().page + '&rows=' + Configuration.get().rows + '&dir=namaAccount&sort=desc&namaAccount=' + this.pencarian).subscribe(table => {                                                     
         this.listData = table.ChartOfAccount;                                                                                                                                                                                                                                                                                                    
        });                                                                                                                                                                                                                                                                                                                                              
      }                                                                                                                                                                                                                                                                                                                                                  
      valuechange(newValue) {                                                                                                                                                                                                                                                                                                                            
        this.report = newValue;                                                                                                                                                                                                                                                                                                                          
      }                                                                                                                                                                                                                                                                                                                                                  
      downloadExel() {                                                                                                                                                                                                                                                                                                                                   
        this.httpService.get(Configuration.get().dataMasterNew + '/chartofaccount/findAll?page='+this.page+'&rows='+this.rows+'&dir=namaAccount&sort=desc').subscribe(table => {                                                                                                                                       
          this.listData = table.ChartOfAccount;                                                                                                                                                                                                                                                                                                   
          this.codes = [];                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                         
          for (let i = 0; i < this.listData.length; i++) {                                                                                                                                                                                                                                                                                               
              this.codes.push({                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                         
                kode: this.listData[i].kode.kode,                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                         
              })                                                                                                                                                                                                                                                                                                                                         
         }                                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                         
          this.fileService.exportAsExcelFile(this.codes, 'chartOfAccount');                                                                                                                                                                                                                                                          
        });                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                         
      }                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                         
      downloadPdf() {                                                                                                                                                                                                                                                                                                                                    
        let cetak = Configuration.get().report + '/chartOfAccount/laporanChartOfAccount.pdf?kdDepartemen='+this.kddept+'&kdProfile='+this.kdprof+'&gambarLogo=' + this.smbrFile +'&download=true';                                                                                                                            
        window.open(cetak);                                                                                                                                                                                                                                                                                                                              
      }                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                         
      confirmDelete() {                                                                                                                                                                                                                                                                                                                                  
        let kode = this.form.get('kode').value;                                                                                                                                                                                                                                                                                                          
        if (kode == null || kode == undefined || kode == "") {                                                                                                                                                                                                                                                                                           
          this.alertService.warn('Peringatan', 'Pilih Daftar Master ChartOfAccount');                                                                                                                                                                                                                                                             
        } else {                                                                                                                                                                                                                                                                                                                                         
          this.confirmationService.confirm({                                                                                                                                                                                                                                                                                                             
            message: 'Apakah data akan di hapus?',                                                                                                                                                                                                                                                                                                       
            header: 'Konfirmasi Hapus',                                                                                                                                                                                                                                                                                                                  
            icon: 'fa fa-trash',                                                                                                                                                                                                                                                                                                                         
           accept: () => {                                                                                                                                                                                                                                                                                                                               
             this.hapus();                                                                                                                                                                                                                                                                                                                               
            },                                                                                                                                                                                                                                                                                                                                           
            reject: () => {                                                                                                                                                                                                                                                                                                                              
              this.alertService.warn('Peringatan', 'Data Tidak Dihapus');                                                                                                                                                                                                                                                                                
            }                                                                                                                                                                                                                                                                                                                                            
          });                                                                                                                                                                                                                                                                                                                                            
        }                                                                                                                                                                                                                                                                                                                                                
      }                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                         
      hapus() {                                                                                                                                                                                                                                                                                                                                          
       let item = [...this.listData];                                                                                                                                                                                                                                                                                                                    
        let deleteItem = item[this.findSelectedIndex()];                                                                                                                                                                                                                                                                                                 
        this.httpService.delete(Configuration.get().dataMasterNew + '/chartofaccount/del/' + deleteItem.kode.kdAccount).subscribe(response => {                                                                                                                                                                                           
          this.alertService.success('Berhasil', 'Data Dihapus');                                                                                                                                                                                                                                                                                         
          this.reset();                                                                                                                                                                                                                                                                                                                                  
        });                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                         
     }                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                         
      findSelectedIndex(): number {                                                                                                                                                                                                                                                                                                                      
        return this.listData.indexOf(this.selected);                                                                                                                                                                                                                                                                                                     
      }                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                         
     reset() {                                                                                                                                                                                                                                                                                                                                          
       this.ngOnInit();                                                                                                                                                                                                                                                                                                                                 
      }                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                         
      confirmUpdate() {                                                                                                                                                                                                                                                                                                                                  
       this.confirmationService.confirm({                                                                                                                                                                                                                                                                                                                
          message: 'Apakah data akan diperbaharui?',                                                                                                                                                                                                                                                                                                     
         header: 'Konfirmasi Pembaharuan',                                                                                                                                                                                                                                                                                                              
          accept: () => {                                                                                                                                                                                                                                                                                                                               
            this.update();                                                                                                                                                                                                                                                                                                                              
          },                                                                                                                                                                                                                                                                                                                                            
          reject: () => {                                                                                                                                                                                                                                                                                                                               
            this.alertService.warn('Peringatan', 'Data Tidak Diperbaharui');                                                                                                                                                                                                                                                                            
          }                                                                                                                                                                                                                                                                                                                                             
        });                                                                                                                                                                                                                                                                                                                                             
      }                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                        
      update() {                                                                                                                                                                                                                                                                                                                                        
        this.httpService.update(Configuration.get().dataMasterNew + '/chartofaccount/update', this.form.value).subscribe(response => {                                                                                                                                                                                              
          this.alertService.success('Berhasil', 'Data Diperbarui');                                                                                                                                                                                                                                                                                     
          // this.get(this.page, this.rows, this.pencarian);                                                                                                                                                                                                                                                                                            
          this.reset();                                                                                                                                                                                                                                                                                                                                 
        });                                                                                                                                                                                                                                                                                                                                             
      }                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                        
      simpan() {                                                                                                                                                                                                                                                                                                                                        
        if (this.formAktif == false) {                                                                                                                                                                                                                                                                                                                  
          this.confirmUpdate()                                                                                                                                                                                                                                                                                                                          
        } else {                                                                                                                                                                                                                                                                                                                                        
          this.httpService.post(Configuration.get().dataMasterNew + '/chartofaccount/save', this.form.value).subscribe(response => {                                                                                                                                                                                                
            this.alertService.success('Berhasil', 'Data Disimpan');                                                                                                                                                                                                                                                                                     
            // this.get(this.page, this.rows, this.pencarian);                                                                                                                                                                                                                                                                                          
            this.reset();                                                                                                                                                                                                                                                                                                                               
          });                                                                                                                                                                                                                                                                                                                                           
        }                                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                        
      }                                                                                                                                                                                                                                                                                                                                                 
      validateAllFormFields(formGroup: FormGroup) {                                                                                                                                                                                                                                                                                                     
        Object.keys(formGroup.controls).forEach(field => {                                                                                                                                                                                                                                                                                              
          const control = formGroup.get(field);                                                                                                                                                                                                                                                                                                         
          if (control instanceof FormControl) {                                                                                                                                                                                                                                                                                                         
            control.markAsTouched({ onlySelf: true });                                                                                                                                                                                                                                                                                                  
          } else if (control instanceof FormGroup) {                                                                                                                                                                                                                                                                                                    
            this.validateAllFormFields(control);                                                                                                                                                                                                                                                                                                        
          }                                                                                                                                                                                                                                                                                                                                             
        });                                                                                                                                                                                                                                                                                                                                             
      }                                                                                                                                                                                                                                                                                                                                                 
      onSubmit() {                                                                                                                                                                                                                                                                                                                                      
        if (this.form.invalid) {                                                                                                                                                                                                                                                                                                                        
          this.validateAllFormFields(this.form);                                                                                                                                                                                                                                                                                                        
          this.alertService.warn("Peringatan", "Data Tidak Sesuai")                                                                                                                                                                                                                                                                                     
        } else {                                                                                                                                                                                                                                                                                                                                        
          this.simpan();                                                                                                                                                                                                                                                                                                                                
        }                                                                                                                                                                                                                                                                                                                                               
      }                                                                                                                                                                                                                                                                                                                                                 
      onRowSelect(event) {                                                                                                                                                                                                                                                                                                                              
        this.formAktif = false;                                                                                                                                                                                                                                                                                                                         
        let cloned = this.clone(event.data);                                                                                                                                                                                                                                                                                                            
        this.form.setValue(cloned);                                                                                                                                                                                                                                                                                                                     
      }                                                                                                                                                                                                                                                                                                                                                 
      clone(cloned: ChartOfAccount): ChartOfAccount {                                                                                                                                                                                                                                                                                                                       
        let hub = new InisialChartOfAccount();                                                                                                                                                                                                                                                                                                   
        for (let prop in cloned) {                                                                                                                                                                                                                                                                                                                      
          hub[prop] = cloned[prop];                                                                                                                                                                                                                                                                                                                     
        }                                                                                                                                                                                                                                                                                                                                               
        let fixHub = new InisialChartOfAccount();                                                                                                                                                                                                                                                                                                
        fixHub = {                                                                                                                                                                                                                                                                                                                                      
         "kode": hub.kode.kdAccount,    
         "noAccount": hub.noAccount,   
         "namaAccount": hub.namaAccount,   
         "reportDisplay": hub.reportDisplay,   
         "saldoNormal": hub.saldoNormal,   
         "kdJenisAccount": hub.kdJenisAccount,   
         "kdKategoryAccount": hub.kdKategoryAccount,   
         "kdStatusAccount": hub.kdStatusAccount,   
         "kdStrukturNomor": hub.kdStrukturNomor,   
         "kdAccountHead": hub.kdAccountHead,   
         "saldoAwalKTahunBerjalan": hub.saldoAwalKTahunBerjalan,   
         "saldoAwalDTahunBerjalan": hub.saldoAwalDTahunBerjalan,   
         "saldoAkhirKTahunBerjalan": hub.saldoAkhirKTahunBerjalan,   
         "saldoAkhirDTahunBerjalan": hub.saldoAkhirDTahunBerjalan,   
         "kodeExternal": hub.kodeExternal,   
         "namaExternal": hub.namaExternal,   
         "statusEnabled": hub.statusEnabled,   
        }                                                                                                                                                                                                                                                                                                                                               
        return fixHub;                                                                                                                                                                                                                                                                                                                                  
      }                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                        
      cetak() {                                                                                                                                                                                                                                                                                                                                         
        this.laporan = true;                                                                                                                                                                                                                                                                                                                            
        this.print.showEmbedPDFReport(Configuration.get().report + '/chartOfAccount/laporanChartOfAccount.pdf?kdDepartemen='+this.kddept+'&kdProfile='+this.kdprof+'&gambarLogo=' + this.smbrFile +'&download=false', 'frmChartOfAccount(_laporanCetak');                                                                               
    }                                                                                                                                                                                                                                                                                                                                                   
    tutupLaporan() {                                                                                                                                                                                                                                                                                                                                    
      this.laporan = false;                                                                                                                                                                                                                                                                                                                             
    }                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                        
    }                                                                                                                                                                                                                                                                                                                                                   
    class InisialChartOfAccount implements ChartOfAccount {                                                                                                                                                                                                                                                                               
      constructor(                                                                                                                                                                                                                                                                                                                                      
        public kode?,          
         public noAccount?,   
         public namaAccount?,   
         public reportDisplay?,   
         public saldoNormal?,   
         public kdJenisAccount?,   
         public kdKategoryAccount?,   
         public kdStatusAccount?,   
         public kdStrukturNomor?,   
         public kdAccountHead?,   
         public saldoAwalKTahunBerjalan?,   
         public saldoAwalDTahunBerjalan?,   
         public saldoAkhirKTahunBerjalan?,   
         public saldoAkhirDTahunBerjalan?,   
         public kodeExternal?,   
         public namaExternal?,   
         public statusEnabled?,   
        )                                                                                                                                                                                                                                                                                                                                               
      { }                                                                                                                                                                                                                                                                                                                                               
    }                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                            

